
services:
  admin-api:
    image: ${ADMIN_API_TAG}:latest
    container_name: admin-api
    ports:
      - "${ADMIN_API_PORT}:${ADMIN_API_PORT}"
    environment:
      CLASSIC_COOKIE_NAME: tapir_session
      CLASSIC_DB_URI: ${CLASSIC_DB_URI}
      CLASSIC_SESSION_HASH: ${CLASSIC_SESSION_HASH}
      SESSION_DURATION: ${CLASSIC_SESSION_DURATION}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${ADMIN_API_PORT}
      ENDORSER_POOL_OBJECT_URL: ${ADMIN_API_ENDORSER_POOL_OBJECT_URL}
      API_SHARED_SECRET: ${ADMIN_API_SHARED_SECRET}
      
    network_mode: host
    volumes:
      - /home/ntai/arxiv/arxiv-admin-console/local:/local

#
  admin-console:
    image: ${ADMIN_CONSOLE_TAG}:latest
    container_name: admin-console
    ports:
      - "${ADMIN_CONSOLE_PORT}:${ADMIN_CONSOLE_PORT}"
    environment:
      PORT: ${ADMIN_CONSOLE_PORT}
      JWT_SECRET: ${JWT_SECRET}
    network_mode: host

