# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from arxiv_admin_api.apis.modapi.modapi_client.models.admin_search_autocomplete_suggestion import AdminSearchAutocompleteSuggestion
from typing import Optional, Set
from typing_extensions import Self

class AdminSearchAutocompleteData(BaseModel):
    """
    AdminSearchAutocompleteData
    """ # noqa: E501
    prefix: Optional[StrictStr] = None
    flag_prefix_valid: Optional[StrictBool] = None
    flag_value_valid: Optional[StrictBool] = None
    value: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    suggestions: Optional[List[AdminSearchAutocompleteSuggestion]] = None
    __properties: ClassVar[List[str]] = ["prefix", "flag_prefix_valid", "flag_value_valid", "value", "description", "suggestions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AdminSearchAutocompleteData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in suggestions (list)
        _items = []
        if self.suggestions:
            for _item_suggestions in self.suggestions:
                if _item_suggestions:
                    _items.append(_item_suggestions.to_dict())
            _dict['suggestions'] = _items
        # set to None if prefix (nullable) is None
        # and model_fields_set contains the field
        if self.prefix is None and "prefix" in self.model_fields_set:
            _dict['prefix'] = None

        # set to None if flag_prefix_valid (nullable) is None
        # and model_fields_set contains the field
        if self.flag_prefix_valid is None and "flag_prefix_valid" in self.model_fields_set:
            _dict['flag_prefix_valid'] = None

        # set to None if flag_value_valid (nullable) is None
        # and model_fields_set contains the field
        if self.flag_value_valid is None and "flag_value_valid" in self.model_fields_set:
            _dict['flag_value_valid'] = None

        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['value'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if suggestions (nullable) is None
        # and model_fields_set contains the field
        if self.suggestions is None and "suggestions" in self.model_fields_set:
            _dict['suggestions'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AdminSearchAutocompleteData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "prefix": obj.get("prefix"),
            "flag_prefix_valid": obj.get("flag_prefix_valid"),
            "flag_value_valid": obj.get("flag_value_valid"),
            "value": obj.get("value"),
            "description": obj.get("description"),
            "suggestions": [AdminSearchAutocompleteSuggestion.from_dict(_item) for _item in obj["suggestions"]] if obj.get("suggestions") is not None else None
        })
        return _obj


