# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from arxiv_admin_api.apis.modapi.modapi_client.models.categories_classifier_scores_inner import CategoriesClassifierScoresInner
from arxiv_admin_api.apis.modapi.modapi_client.models.proposals import Proposals
from arxiv_admin_api.apis.modapi.modapi_client.models.submission_classification import SubmissionClassification
from typing import Optional, Set
from typing_extensions import Self

class Categories(BaseModel):
    """
    Categories
    """ # noqa: E501
    classifier_scores: List[CategoriesClassifierScoresInner]
    submission: SubmissionClassification
    new_crosses: List[StrictStr]
    proposals: Proposals
    __properties: ClassVar[List[str]] = ["classifier_scores", "submission", "new_crosses", "proposals"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Categories from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in classifier_scores (list)
        _items = []
        if self.classifier_scores:
            for _item_classifier_scores in self.classifier_scores:
                if _item_classifier_scores:
                    _items.append(_item_classifier_scores.to_dict())
            _dict['classifier_scores'] = _items
        # override the default output from pydantic by calling `to_dict()` of submission
        if self.submission:
            _dict['submission'] = self.submission.to_dict()
        # override the default output from pydantic by calling `to_dict()` of proposals
        if self.proposals:
            _dict['proposals'] = self.proposals.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Categories from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "classifier_scores": [CategoriesClassifierScoresInner.from_dict(_item) for _item in obj["classifier_scores"]] if obj.get("classifier_scores") is not None else None,
            "submission": SubmissionClassification.from_dict(obj["submission"]) if obj.get("submission") is not None else None,
            "new_crosses": obj.get("new_crosses"),
            "proposals": Proposals.from_dict(obj["proposals"]) if obj.get("proposals") is not None else None
        })
        return _obj


