# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from arxiv_admin_api.apis.modapi.modapi_client.models.check_result_summary import CheckResultSummary
from typing import Optional, Set
from typing_extensions import Self

class CheckSummary(BaseModel):
    """
    CheckSummary
    """ # noqa: E501
    check_id: StrictInt
    check_name: StrictStr
    latest_result: Optional[CheckResultSummary] = None
    outdated_result_with_response: Optional[CheckResultSummary] = None
    __properties: ClassVar[List[str]] = ["check_id", "check_name", "latest_result", "outdated_result_with_response"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CheckSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of latest_result
        if self.latest_result:
            _dict['latest_result'] = self.latest_result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of outdated_result_with_response
        if self.outdated_result_with_response:
            _dict['outdated_result_with_response'] = self.outdated_result_with_response.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CheckSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "check_id": obj.get("check_id"),
            "check_name": obj.get("check_name"),
            "latest_result": CheckResultSummary.from_dict(obj["latest_result"]) if obj.get("latest_result") is not None else None,
            "outdated_result_with_response": CheckResultSummary.from_dict(obj["outdated_result_with_response"]) if obj.get("outdated_result_with_response") is not None else None
        })
        return _obj


