# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from arxiv_admin_api.apis.modapi.modapi_client.models.admin_discussion import AdminDiscussion
from arxiv_admin_api.apis.modapi.modapi_client.models.mod_hold_in import ModHoldIn
from arxiv_admin_api.apis.modapi.modapi_client.models.reject import Reject
from arxiv_admin_api.apis.modapi.modapi_client.models.reject_other import RejectOther
from arxiv_admin_api.apis.modapi.modapi_client.models.send_to_admin_other import SendToAdminOther
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

HOLD_ANY_OF_SCHEMAS = ["AdminDiscussion", "ModHoldIn", "Reject", "RejectOther", "SendToAdminOther"]

class Hold(BaseModel):
    """
    Hold
    """

    # data type: ModHoldIn
    anyof_schema_1_validator: Optional[ModHoldIn] = None
    # data type: Reject
    anyof_schema_2_validator: Optional[Reject] = None
    # data type: RejectOther
    anyof_schema_3_validator: Optional[RejectOther] = None
    # data type: SendToAdminOther
    anyof_schema_4_validator: Optional[SendToAdminOther] = None
    # data type: AdminDiscussion
    anyof_schema_5_validator: Optional[AdminDiscussion] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[AdminDiscussion, ModHoldIn, Reject, RejectOther, SendToAdminOther]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "AdminDiscussion", "ModHoldIn", "Reject", "RejectOther", "SendToAdminOther" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = Hold.model_construct()
        error_messages = []
        # validate data type: ModHoldIn
        if not isinstance(v, ModHoldIn):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ModHoldIn`")
        else:
            return v

        # validate data type: Reject
        if not isinstance(v, Reject):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Reject`")
        else:
            return v

        # validate data type: RejectOther
        if not isinstance(v, RejectOther):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RejectOther`")
        else:
            return v

        # validate data type: SendToAdminOther
        if not isinstance(v, SendToAdminOther):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SendToAdminOther`")
        else:
            return v

        # validate data type: AdminDiscussion
        if not isinstance(v, AdminDiscussion):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AdminDiscussion`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in Hold with anyOf schemas: AdminDiscussion, ModHoldIn, Reject, RejectOther, SendToAdminOther. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[ModHoldIn] = None
        try:
            instance.actual_instance = ModHoldIn.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[Reject] = None
        try:
            instance.actual_instance = Reject.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[RejectOther] = None
        try:
            instance.actual_instance = RejectOther.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[SendToAdminOther] = None
        try:
            instance.actual_instance = SendToAdminOther.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[AdminDiscussion] = None
        try:
            instance.actual_instance = AdminDiscussion.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Hold with anyOf schemas: AdminDiscussion, ModHoldIn, Reject, RejectOther, SendToAdminOther. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AdminDiscussion, ModHoldIn, Reject, RejectOther, SendToAdminOther]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


