# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from arxiv_admin_api.apis.modapi.modapi_client.models.moderator_prefs_groups import ModeratorPrefsGroups
from typing import Optional, Set
from typing_extensions import Self

class Mod(BaseModel):
    """
    Mod
    """ # noqa: E501
    user_id: StrictInt
    username: StrictStr
    name: StrictStr
    email: StrictStr
    moderated_categories: List[StrictStr]
    moderated_archives: Optional[List[StrictStr]] = None
    moderator_prefs: Optional[ModeratorPrefsGroups] = None
    __properties: ClassVar[List[str]] = ["user_id", "username", "name", "email", "moderated_categories", "moderated_archives", "moderator_prefs"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Mod from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of moderator_prefs
        if self.moderator_prefs:
            _dict['moderator_prefs'] = self.moderator_prefs.to_dict()
        # set to None if moderated_archives (nullable) is None
        # and model_fields_set contains the field
        if self.moderated_archives is None and "moderated_archives" in self.model_fields_set:
            _dict['moderated_archives'] = None

        # set to None if moderator_prefs (nullable) is None
        # and model_fields_set contains the field
        if self.moderator_prefs is None and "moderator_prefs" in self.model_fields_set:
            _dict['moderator_prefs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Mod from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_id": obj.get("user_id"),
            "username": obj.get("username"),
            "name": obj.get("name"),
            "email": obj.get("email"),
            "moderated_categories": obj.get("moderated_categories"),
            "moderated_archives": obj.get("moderated_archives"),
            "moderator_prefs": ModeratorPrefsGroups.from_dict(obj["moderator_prefs"]) if obj.get("moderator_prefs") is not None else None
        })
        return _obj


