# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import StrictBool, StrictInt, StrictStr
from typing import Any, List, Optional
from arxiv_admin_api.apis.modapi.modapi_client.models.get_hold_holds_submission_id_get200_response_inner_inner import GetHoldHoldsSubmissionIdGet200ResponseInnerInner
from arxiv_admin_api.apis.modapi.modapi_client.models.hold import Hold
from arxiv_admin_api.apis.modapi.modapi_client.models.hold_release_status import HoldReleaseStatus

from arxiv_admin_api.apis.modapi.modapi_client.api_client import ApiClient, RequestSerialized
from arxiv_admin_api.apis.modapi.modapi_client.api_response import ApiResponse
from arxiv_admin_api.apis.modapi.modapi_client.rest import RESTResponseType


class HoldsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def hold_holds_submission_id_get(
        self,
        submission_id: StrictInt,
        authorization: Optional[StrictStr] = None,
        modkey: Optional[StrictStr] = None,
        arxivng_session_id: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[List[GetHoldHoldsSubmissionIdGet200ResponseInnerInner]]:
        """Get Hold

        Gets the hold for a single submission.

        :param submission_id: (required)
        :type submission_id: int
        :param authorization:
        :type authorization: str
        :param modkey:
        :type modkey: str
        :param arxivng_session_id:
        :type arxivng_session_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._hold_holds_submission_id_get_serialize(
            submission_id=submission_id,
            authorization=authorization,
            modkey=modkey,
            arxivng_session_id=arxivng_session_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[List[GetHoldHoldsSubmissionIdGet200ResponseInnerInner]]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def hold_holds_submission_id_get_with_http_info(
        self,
        submission_id: StrictInt,
        authorization: Optional[StrictStr] = None,
        modkey: Optional[StrictStr] = None,
        arxivng_session_id: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[List[GetHoldHoldsSubmissionIdGet200ResponseInnerInner]]]:
        """Get Hold

        Gets the hold for a single submission.

        :param submission_id: (required)
        :type submission_id: int
        :param authorization:
        :type authorization: str
        :param modkey:
        :type modkey: str
        :param arxivng_session_id:
        :type arxivng_session_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._hold_holds_submission_id_get_serialize(
            submission_id=submission_id,
            authorization=authorization,
            modkey=modkey,
            arxivng_session_id=arxivng_session_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[List[GetHoldHoldsSubmissionIdGet200ResponseInnerInner]]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def hold_holds_submission_id_get_without_preload_content(
        self,
        submission_id: StrictInt,
        authorization: Optional[StrictStr] = None,
        modkey: Optional[StrictStr] = None,
        arxivng_session_id: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Hold

        Gets the hold for a single submission.

        :param submission_id: (required)
        :type submission_id: int
        :param authorization:
        :type authorization: str
        :param modkey:
        :type modkey: str
        :param arxivng_session_id:
        :type arxivng_session_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._hold_holds_submission_id_get_serialize(
            submission_id=submission_id,
            authorization=authorization,
            modkey=modkey,
            arxivng_session_id=arxivng_session_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[List[GetHoldHoldsSubmissionIdGet200ResponseInnerInner]]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _hold_holds_submission_id_get_serialize(
        self,
        submission_id,
        authorization,
        modkey,
        arxivng_session_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if submission_id is not None:
            _path_params['submission_id'] = submission_id
        # process the query parameters
        # process the header parameters
        if authorization is not None:
            _header_params['Authorization'] = authorization
        if modkey is not None:
            _header_params['modkey'] = modkey
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/holds/{submission_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def holds_get(
        self,
        authorization: Optional[StrictStr] = None,
        modkey: Optional[StrictStr] = None,
        arxivng_session_id: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[List[GetHoldHoldsSubmissionIdGet200ResponseInnerInner]]:
        """Holds

        Gets all existing holds.  If the user is a moderator this only gets the holds on submissions of interest to the moderator.  Returns List of [ subid, user_id, type, reason ]  user_id, and reason may be an empty string.  Type will be 'admin', 'mod' or 'legacy'.

        :param authorization:
        :type authorization: str
        :param modkey:
        :type modkey: str
        :param arxivng_session_id:
        :type arxivng_session_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._holds_get_serialize(
            authorization=authorization,
            modkey=modkey,
            arxivng_session_id=arxivng_session_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[List[GetHoldHoldsSubmissionIdGet200ResponseInnerInner]]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def holds_get_with_http_info(
        self,
        authorization: Optional[StrictStr] = None,
        modkey: Optional[StrictStr] = None,
        arxivng_session_id: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[List[GetHoldHoldsSubmissionIdGet200ResponseInnerInner]]]:
        """Holds

        Gets all existing holds.  If the user is a moderator this only gets the holds on submissions of interest to the moderator.  Returns List of [ subid, user_id, type, reason ]  user_id, and reason may be an empty string.  Type will be 'admin', 'mod' or 'legacy'.

        :param authorization:
        :type authorization: str
        :param modkey:
        :type modkey: str
        :param arxivng_session_id:
        :type arxivng_session_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._holds_get_serialize(
            authorization=authorization,
            modkey=modkey,
            arxivng_session_id=arxivng_session_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[List[GetHoldHoldsSubmissionIdGet200ResponseInnerInner]]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def holds_get_without_preload_content(
        self,
        authorization: Optional[StrictStr] = None,
        modkey: Optional[StrictStr] = None,
        arxivng_session_id: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Holds

        Gets all existing holds.  If the user is a moderator this only gets the holds on submissions of interest to the moderator.  Returns List of [ subid, user_id, type, reason ]  user_id, and reason may be an empty string.  Type will be 'admin', 'mod' or 'legacy'.

        :param authorization:
        :type authorization: str
        :param modkey:
        :type modkey: str
        :param arxivng_session_id:
        :type arxivng_session_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._holds_get_serialize(
            authorization=authorization,
            modkey=modkey,
            arxivng_session_id=arxivng_session_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[List[GetHoldHoldsSubmissionIdGet200ResponseInnerInner]]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _holds_get_serialize(
        self,
        authorization,
        modkey,
        arxivng_session_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if authorization is not None:
            _header_params['Authorization'] = authorization
        if modkey is not None:
            _header_params['modkey'] = modkey
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/holds',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def release_submission_submission_id_hold_release_post(
        self,
        submission_id: StrictInt,
        hold_release_status: Optional[HoldReleaseStatus] = None,
        enable_submission_locks: Optional[StrictBool] = None,
        authorization: Optional[StrictStr] = None,
        modkey: Optional[StrictStr] = None,
        arxivng_session_id: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> str:
        """Hold Release

        Releases a hold.  To release a hold means to set the submission status so that it is available to be published.  If Moderator the submission must be: - on hold - have a row in arXiv_submission_hold_reason  Moderators can release any hold that has a reason in the arXiv_submission_hold_reason table.  If Admin the submission must be: - on hold  Admins can release holds referenced in the arXiv_submission_hold_reason or legacy style holds.

        :param submission_id: (required)
        :type submission_id: int
        :param hold_release_status:
        :type hold_release_status: HoldReleaseStatus
        :param enable_submission_locks:
        :type enable_submission_locks: bool
        :param authorization:
        :type authorization: str
        :param modkey:
        :type modkey: str
        :param arxivng_session_id:
        :type arxivng_session_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._release_submission_submission_id_hold_release_post_serialize(
            submission_id=submission_id,
            hold_release_status=hold_release_status,
            enable_submission_locks=enable_submission_locks,
            authorization=authorization,
            modkey=modkey,
            arxivng_session_id=arxivng_session_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def release_submission_submission_id_hold_release_post_with_http_info(
        self,
        submission_id: StrictInt,
        hold_release_status: Optional[HoldReleaseStatus] = None,
        enable_submission_locks: Optional[StrictBool] = None,
        authorization: Optional[StrictStr] = None,
        modkey: Optional[StrictStr] = None,
        arxivng_session_id: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[str]:
        """Hold Release

        Releases a hold.  To release a hold means to set the submission status so that it is available to be published.  If Moderator the submission must be: - on hold - have a row in arXiv_submission_hold_reason  Moderators can release any hold that has a reason in the arXiv_submission_hold_reason table.  If Admin the submission must be: - on hold  Admins can release holds referenced in the arXiv_submission_hold_reason or legacy style holds.

        :param submission_id: (required)
        :type submission_id: int
        :param hold_release_status:
        :type hold_release_status: HoldReleaseStatus
        :param enable_submission_locks:
        :type enable_submission_locks: bool
        :param authorization:
        :type authorization: str
        :param modkey:
        :type modkey: str
        :param arxivng_session_id:
        :type arxivng_session_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._release_submission_submission_id_hold_release_post_serialize(
            submission_id=submission_id,
            hold_release_status=hold_release_status,
            enable_submission_locks=enable_submission_locks,
            authorization=authorization,
            modkey=modkey,
            arxivng_session_id=arxivng_session_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def release_submission_submission_id_hold_release_post_without_preload_content(
        self,
        submission_id: StrictInt,
        hold_release_status: Optional[HoldReleaseStatus] = None,
        enable_submission_locks: Optional[StrictBool] = None,
        authorization: Optional[StrictStr] = None,
        modkey: Optional[StrictStr] = None,
        arxivng_session_id: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Hold Release

        Releases a hold.  To release a hold means to set the submission status so that it is available to be published.  If Moderator the submission must be: - on hold - have a row in arXiv_submission_hold_reason  Moderators can release any hold that has a reason in the arXiv_submission_hold_reason table.  If Admin the submission must be: - on hold  Admins can release holds referenced in the arXiv_submission_hold_reason or legacy style holds.

        :param submission_id: (required)
        :type submission_id: int
        :param hold_release_status:
        :type hold_release_status: HoldReleaseStatus
        :param enable_submission_locks:
        :type enable_submission_locks: bool
        :param authorization:
        :type authorization: str
        :param modkey:
        :type modkey: str
        :param arxivng_session_id:
        :type arxivng_session_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._release_submission_submission_id_hold_release_post_serialize(
            submission_id=submission_id,
            hold_release_status=hold_release_status,
            enable_submission_locks=enable_submission_locks,
            authorization=authorization,
            modkey=modkey,
            arxivng_session_id=arxivng_session_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _release_submission_submission_id_hold_release_post_serialize(
        self,
        submission_id,
        hold_release_status,
        enable_submission_locks,
        authorization,
        modkey,
        arxivng_session_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if submission_id is not None:
            _path_params['submission_id'] = submission_id
        # process the query parameters
        if hold_release_status is not None:
            
            _query_params.append(('hold_release_status', hold_release_status.value))
            
        if enable_submission_locks is not None:
            
            _query_params.append(('enable_submission_locks', enable_submission_locks))
            
        # process the header parameters
        if authorization is not None:
            _header_params['Authorization'] = authorization
        if modkey is not None:
            _header_params['modkey'] = modkey
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/submission/{submission_id}/hold/release',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def submission_submission_id_hold_post(
        self,
        submission_id: StrictInt,
        hold: Hold,
        enable_submission_locks: Optional[StrictBool] = None,
        authorization: Optional[StrictStr] = None,
        modkey: Optional[StrictStr] = None,
        arxivng_session_id: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> object:
        """Hold

        Put a submission on hold This will prevent it from being announced until it is released from hold. The sendback feature is not yet implemented.

        :param submission_id: (required)
        :type submission_id: int
        :param hold: (required)
        :type hold: Hold
        :param enable_submission_locks:
        :type enable_submission_locks: bool
        :param authorization:
        :type authorization: str
        :param modkey:
        :type modkey: str
        :param arxivng_session_id:
        :type arxivng_session_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._submission_submission_id_hold_post_serialize(
            submission_id=submission_id,
            hold=hold,
            enable_submission_locks=enable_submission_locks,
            authorization=authorization,
            modkey=modkey,
            arxivng_session_id=arxivng_session_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def submission_submission_id_hold_post_with_http_info(
        self,
        submission_id: StrictInt,
        hold: Hold,
        enable_submission_locks: Optional[StrictBool] = None,
        authorization: Optional[StrictStr] = None,
        modkey: Optional[StrictStr] = None,
        arxivng_session_id: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[object]:
        """Hold

        Put a submission on hold This will prevent it from being announced until it is released from hold. The sendback feature is not yet implemented.

        :param submission_id: (required)
        :type submission_id: int
        :param hold: (required)
        :type hold: Hold
        :param enable_submission_locks:
        :type enable_submission_locks: bool
        :param authorization:
        :type authorization: str
        :param modkey:
        :type modkey: str
        :param arxivng_session_id:
        :type arxivng_session_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._submission_submission_id_hold_post_serialize(
            submission_id=submission_id,
            hold=hold,
            enable_submission_locks=enable_submission_locks,
            authorization=authorization,
            modkey=modkey,
            arxivng_session_id=arxivng_session_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def submission_submission_id_hold_post_without_preload_content(
        self,
        submission_id: StrictInt,
        hold: Hold,
        enable_submission_locks: Optional[StrictBool] = None,
        authorization: Optional[StrictStr] = None,
        modkey: Optional[StrictStr] = None,
        arxivng_session_id: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Hold

        Put a submission on hold This will prevent it from being announced until it is released from hold. The sendback feature is not yet implemented.

        :param submission_id: (required)
        :type submission_id: int
        :param hold: (required)
        :type hold: Hold
        :param enable_submission_locks:
        :type enable_submission_locks: bool
        :param authorization:
        :type authorization: str
        :param modkey:
        :type modkey: str
        :param arxivng_session_id:
        :type arxivng_session_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._submission_submission_id_hold_post_serialize(
            submission_id=submission_id,
            hold=hold,
            enable_submission_locks=enable_submission_locks,
            authorization=authorization,
            modkey=modkey,
            arxivng_session_id=arxivng_session_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "object",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _submission_submission_id_hold_post_serialize(
        self,
        submission_id,
        hold,
        enable_submission_locks,
        authorization,
        modkey,
        arxivng_session_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if submission_id is not None:
            _path_params['submission_id'] = submission_id
        # process the query parameters
        if enable_submission_locks is not None:
            
            _query_params.append(('enable_submission_locks', enable_submission_locks))
            
        # process the header parameters
        if authorization is not None:
            _header_params['Authorization'] = authorization
        if modkey is not None:
            _header_params['modkey'] = modkey
        # process the form parameters
        # process the body parameter
        if hold is not None:
            _body_params = hold


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/submission/{submission_id}/hold',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


