FROM nginx:alpine AS production
WORKDIR /app
COPY ./build /usr/share/nginx/html/admin-console
COPY ./src /usr/share/nginx/html/src
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx.sh /
RUN chmod +x /nginx.sh
EXPOSE 21511
CMD /nginx.sh
