"""Countries route"""

from typing import Optional, List

from fastapi import APIRouter, HTTPException, status, Query, Response
from pydantic import BaseModel, ConfigDict
from arxiv.base import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/countries", tags=["metadata"])

COUNTRIES: List[dict] = [
  {
    "name": "United States",
    "iso2": "US",
    "iso3": "USA",
    "Top Level Domain": "us",
    "FIPS": "US",
    "iso_numeric": 840,
    "GeoNameID": 6252001,
    "E164": 1,
    "phone_code": 1,
    "continent": "North America",
    "Capital": "Washington",
    "Time Zone in Capital": "America/New_York",
    "Currency": "Dollar",
    "Language Codes": "en-US,es-US,haw,fr",
    "Area KM2": 9629091,
  },
  {
    "name": "Afghanistan",
    "iso2": "AF",
    "iso3": "AFG",
    "Top Level Domain": "af",
    "FIPS": "AF",
    "iso_numeric": "004",
    "GeoNameID": 1149361,
    "E164": 93,
    "phone_code": 93,
    "continent": "Asia",
    "Capital": "Kabul",
    "Time Zone in Capital": "Asia/Kabul",
    "Currency": "Afghani",
    "Language Codes": "fa-AF,ps,uz-AF,tk",
    "Area KM2": 647500,
  },
  {
    "name": "Albania",
    "iso2": "AL",
    "iso3": "ALB",
    "Top Level Domain": "al",
    "FIPS": "AL",
    "iso_numeric": "008",
    "GeoNameID": 783754,
    "E164": 355,
    "phone_code": 355,
    "continent": "Europe",
    "Capital": "Tirana",
    "Time Zone in Capital": "Europe/Tirane",
    "Currency": "Lek",
    "Language Codes": "sq,el",
  },
  {
    "name": "Algeria",
    "iso2": "DZ",
    "iso3": "DZA",
    "Top Level Domain": "dz",
    "FIPS": "AG",
    "iso_numeric": "012",
    "GeoNameID": 2589581,
    "E164": 213,
    "phone_code": 213,
    "continent": "Africa",
    "Capital": "Algiers",
    "Time Zone in Capital": "Africa/Algiers",
    "Currency": "Dinar",
    "Language Codes": "ar-DZ",
    "Area KM2": 2381740,
  },
  {
    "name": "American Samoa",
    "iso2": "AS",
    "iso3": "ASM",
    "Top Level Domain": "as",
    "FIPS": "AQ",
    "iso_numeric": "016",
    "GeoNameID": 5880801,
    "E164": 1,
    "phone_code": "1-684",
    "continent": "Oceania",
    "Capital": "Pago Pago",
    "Time Zone in Capital": "Pacific/Pago_Pago",
    "Currency": "Dollar",
    "Language Codes": "en-AS,sm,to",
    "Area KM2": 199,
  },
  {
    "name": "Andorra",
    "iso2": "AD",
    "iso3": "AND",
    "Top Level Domain": "ad",
    "FIPS": "AN",
    "iso_numeric": "020",
    "GeoNameID": 3041565,
    "E164": 376,
    "phone_code": 376,
    "continent": "Europe",
    "Capital": "Andorra la Vella",
    "Time Zone in Capital": "Europe/Andorra",
    "Currency": "Euro",
    "Language Codes": "ca",
    "Area KM2": 468,
  },
  {
    "name": "Angola",
    "iso2": "AO",
    "iso3": "AGO",
    "Top Level Domain": "ao",
    "FIPS": "AO",
    "iso_numeric": "024",
    "GeoNameID": 3351879,
    "E164": 244,
    "phone_code": 244,
    "continent": "Africa",
    "Capital": "Luanda",
    "Time Zone in Capital": "Africa/Lagos",
    "Currency": "Kwanza",
    "Language Codes": "pt-AO",
    "Area KM2": 1246700,
  },
  {
    "name": "Anguilla",
    "iso2": "AI",
    "iso3": "AIA",
    "Top Level Domain": "ai",
    "FIPS": "AV",
    "iso_numeric": 660,
    "GeoNameID": 3573511,
    "E164": 1,
    "phone_code": "1-264",
    "continent": "North America",
    "Capital": "The Valley",
    "Time Zone in Capital": "America/Port_of_Spain",
    "Currency": "Dollar",
    "Language Codes": "en-AI",
    "Area KM2": 102,
  },
  {
    "name": "Antarctica",
    "iso2": "AQ",
    "iso3": "ATA",
    "Top Level Domain": "aq",
    "FIPS": "AY",
    "iso_numeric": "010",
    "GeoNameID": 6697173,
    "E164": 672,
    "phone_code": 672,
    "continent": "Antarctica",
    "Capital": "",
    "Time Zone in Capital": "Antarctica/Troll",
    "Currency": "",
    "Language Codes": "",
    "Area KM2": 14000000,
  },
  {
    "name": "Antigua and Barbuda",
    "iso2": "AG",
    "iso3": "ATG",
    "Top Level Domain": "ag",
    "FIPS": "AC",
    "iso_numeric": "028",
    "GeoNameID": 3576396,
    "E164": 1,
    "phone_code": "1-268",
    "continent": "North America",
    "Capital": "St. John's",
    "Time Zone in Capital": "America/Antigua",
    "Currency": "Dollar",
    "Language Codes": "en-AG",
    "Area KM2": 443,
  },
  {
    "name": "Argentina",
    "iso2": "AR",
    "iso3": "ARG",
    "Top Level Domain": "ar",
    "FIPS": "AR",
    "iso_numeric": "032",
    "GeoNameID": 3865483,
    "E164": 54,
    "phone_code": 54,
    "continent": "South America",
    "Capital": "Buenos Aires",
    "Time Zone in Capital": "America/Argentina/Buenos_Aires",
    "Currency": "Peso",
    "Language Codes": "es-AR,en,it,de,fr,gn",
    "Area KM2": 2766890,
  },
  {
    "name": "Armenia",
    "iso2": "AM",
    "iso3": "ARM",
    "Top Level Domain": "am",
    "FIPS": "AM",
    "iso_numeric": "051",
    "GeoNameID": 174982,
    "E164": 374,
    "phone_code": 374,
    "continent": "Asia",
    "Capital": "Yerevan",
    "Time Zone in Capital": "Asia/Yerevan",
    "Currency": "Dram",
    "Language Codes": "hy",
    "Area KM2": 29800,
  },
  {
    "name": "Aruba",
    "iso2": "AW",
    "iso3": "ABW",
    "Top Level Domain": "aw",
    "FIPS": "AA",
    "iso_numeric": 533,
    "GeoNameID": 3577279,
    "E164": 297,
    "phone_code": 297,
    "continent": "North America",
    "Capital": "Oranjestad",
    "Time Zone in Capital": "America/Curacao",
    "Currency": "Guilder",
    "Language Codes": "nl-AW,es,en",
    "Area KM2": 193,
  },
  {
    "name": "Australia",
    "iso2": "AU",
    "iso3": "AUS",
    "Top Level Domain": "au",
    "FIPS": "AS",
    "iso_numeric": "036",
    "GeoNameID": 2077456,
    "E164": 61,
    "phone_code": 61,
    "continent": "Oceania",
    "Capital": "Canberra",
    "Time Zone in Capital": "Australia/Sydney",
    "Currency": "Dollar",
    "Language Codes": "en-AU",
    "Area KM2": 7686850,
  },
  {
    "name": "Austria",
    "iso2": "AT",
    "iso3": "AUT",
    "Top Level Domain": "at",
    "FIPS": "AU",
    "iso_numeric": "040",
    "GeoNameID": 2782113,
    "E164": 43,
    "phone_code": 43,
    "continent": "Europe",
    "Capital": "Vienna",
    "Time Zone in Capital": "Europe/Vienna",
    "Currency": "Euro",
    "Language Codes": "de-AT,hr,hu,sl",
    "Area KM2": 83858,
  },
  {
    "name": "Azerbaijan",
    "iso2": "AZ",
    "iso3": "AZE",
    "Top Level Domain": "az",
    "FIPS": "AJ",
    "iso_numeric": "031",
    "GeoNameID": 587116,
    "E164": 994,
    "phone_code": 994,
    "continent": "Asia",
    "Capital": "Baku",
    "Time Zone in Capital": "Asia/Baku",
    "Currency": "Manat",
    "Language Codes": "az,ru,hy",
    "Area KM2": 86600,
  },
  {
    "name": "Bahamas",
    "iso2": "BS",
    "iso3": "BHS",
    "Top Level Domain": "bs",
    "FIPS": "BF",
    "iso_numeric": "044",
    "GeoNameID": 3572887,
    "E164": 1,
    "phone_code": "1-242",
    "continent": "North America",
    "Capital": "Nassau",
    "Time Zone in Capital": "America/Nassau",
    "Currency": "Dollar",
    "Language Codes": "en-BS",
    "Area KM2": 13940,
  },
  {
    "name": "Bahrain",
    "iso2": "BH",
    "iso3": "BHR",
    "Top Level Domain": "bh",
    "FIPS": "BA",
    "iso_numeric": "048",
    "GeoNameID": 290291,
    "E164": 973,
    "phone_code": 973,
    "continent": "Asia",
    "Capital": "Manama",
    "Time Zone in Capital": "Asia/Bahrain",
    "Currency": "Dinar",
    "Language Codes": "ar-BH,en,fa,ur",
    "Area KM2": 665,
  },
  {
    "name": "Bangladesh",
    "iso2": "BD",
    "iso3": "BGD",
    "Top Level Domain": "bd",
    "FIPS": "BG",
    "iso_numeric": "050",
    "GeoNameID": 1210997,
    "E164": 880,
    "phone_code": 880,
    "continent": "Asia",
    "Capital": "Dhaka",
    "Time Zone in Capital": "Asia/Dhaka",
    "Currency": "Taka",
    "Language Codes": "bn-BD,en",
    "Area KM2": 144000,
  },
  {
    "name": "Barbados",
    "iso2": "BB",
    "iso3": "BRB",
    "Top Level Domain": "bb",
    "FIPS": "BB",
    "iso_numeric": "052",
    "GeoNameID": 3374084,
    "E164": 1,
    "phone_code": "1-246",
    "continent": "North America",
    "Capital": "Bridgetown",
    "Time Zone in Capital": "America/Barbados",
    "Currency": "Dollar",
    "Language Codes": "en-BB",
    "Area KM2": 431,
  },
  {
    "name": "Belarus",
    "iso2": "BY",
    "iso3": "BLR",
    "Top Level Domain": "by",
    "FIPS": "BO",
    "iso_numeric": 112,
    "GeoNameID": 630336,
    "E164": 375,
    "phone_code": 375,
    "continent": "Europe",
    "Capital": "Minsk",
    "Time Zone in Capital": "Europe/Minsk",
    "Currency": "Ruble",
    "Language Codes": "be,ru",
    "Area KM2": 207600,
  },
  {
    "name": "Belgium",
    "iso2": "BE",
    "iso3": "BEL",
    "Top Level Domain": "be",
    "FIPS": "BE",
    "iso_numeric": "056",
    "GeoNameID": 2802361,
    "E164": 32,
    "phone_code": 32,
    "continent": "Europe",
    "Capital": "Brussels",
    "Time Zone in Capital": "Europe/Brussels",
    "Currency": "Euro",
    "Language Codes": "nl-BE,fr-BE,de-BE",
    "Area KM2": 30510,
  },
  {
    "name": "Belize",
    "iso2": "BZ",
    "iso3": "BLZ",
    "Top Level Domain": "bz",
    "FIPS": "BH",
    "iso_numeric": "084",
    "GeoNameID": 3582678,
    "E164": 501,
    "phone_code": 501,
    "continent": "North America",
    "Capital": "Belmopan",
    "Time Zone in Capital": "America/Belize",
    "Currency": "Dollar",
    "Language Codes": "en-BZ,es",
    "Area KM2": 22966,
  },
  {
    "name": "Benin",
    "iso2": "BJ",
    "iso3": "BEN",
    "Top Level Domain": "bj",
    "FIPS": "BN",
    "iso_numeric": 204,
    "GeoNameID": 2395170,
    "E164": 229,
    "phone_code": 229,
    "continent": "Africa",
    "Capital": "Porto-Novo",
    "Time Zone in Capital": "Africa/Lagos",
    "Currency": "Franc",
    "Language Codes": "fr-BJ",
    "Area KM2": 112620,
  },
  {
    "name": "Bermuda",
    "iso2": "BM",
    "iso3": "BMU",
    "Top Level Domain": "bm",
    "FIPS": "BD",
    "iso_numeric": "060",
    "GeoNameID": 3573345,
    "E164": 1,
    "phone_code": "1-441",
    "continent": "North America",
    "Capital": "Hamilton",
    "Time Zone in Capital": "Atlantic/Bermuda",
    "Currency": "Dollar",
    "Language Codes": "en-BM,pt",
    "Area KM2": 53,
  },
  {
    "name": "Bhutan",
    "iso2": "BT",
    "iso3": "BTN",
    "Top Level Domain": "bt",
    "FIPS": "BT",
    "iso_numeric": "064",
    "GeoNameID": 1252634,
    "E164": 975,
    "phone_code": 975,
    "continent": "Asia",
    "Capital": "Thimphu",
    "Time Zone in Capital": "Asia/Thimphu",
    "Currency": "Ngultrum",
    "Language Codes": "dz",
    "Area KM2": 47000,
  },
  {
    "name": "Bolivia",
    "iso2": "BO",
    "iso3": "BOL",
    "Top Level Domain": "bo",
    "FIPS": "BL",
    "iso_numeric": "068",
    "GeoNameID": 3923057,
    "E164": 591,
    "phone_code": 591,
    "continent": "South America",
    "Capital": "Sucre",
    "Time Zone in Capital": "America/La_Paz",
    "Currency": "Boliviano",
    "Language Codes": "es-BO,qu,ay",
    "Area KM2": 1098580,
  },
  {
    "name": "Bosnia and Herzegovina",
    "iso2": "BA",
    "iso3": "BIH",
    "Top Level Domain": "ba",
    "FIPS": "BK",
    "iso_numeric": "070",
    "GeoNameID": 3277605,
    "E164": 387,
    "phone_code": 387,
    "continent": "Europe",
    "Capital": "Sarajevo",
    "Time Zone in Capital": "Europe/Belgrade",
    "Currency": "Marka",
    "Language Codes": "bs,hr-BA,sr-BA",
    "Area KM2": 51129,
  },
  {
    "name": "Botswana",
    "iso2": "BW",
    "iso3": "BWA",
    "Top Level Domain": "bw",
    "FIPS": "BC",
    "iso_numeric": "072",
    "GeoNameID": 933860,
    "E164": 267,
    "phone_code": 267,
    "continent": "Africa",
    "Capital": "Gaborone",
    "Time Zone in Capital": "Africa/Maputo",
    "Currency": "Pula",
    "Language Codes": "en-BW,tn-BW",
    "Area KM2": 600370,
  },
  {
    "name": "Brazil",
    "iso2": "BR",
    "iso3": "BRA",
    "Top Level Domain": "br",
    "FIPS": "BR",
    "iso_numeric": "076",
    "GeoNameID": 3469034,
    "E164": 55,
    "phone_code": 55,
    "continent": "South America",
    "Capital": "Brasilia",
    "Time Zone in Capital": "America/Sao_Paulo",
    "Currency": "Real",
    "Language Codes": "pt-BR,es,en,fr",
    "Area KM2": 8511965,
  },
  {
    "name": "British Indian Ocean Territory",
    "iso2": "IO",
    "iso3": "IOT",
    "Top Level Domain": "io",
    "FIPS": "IO",
    "iso_numeric": "086",
    "GeoNameID": 1282588,
    "E164": 246,
    "phone_code": 246,
    "continent": "Asia",
    "Capital": "Diego Garcia",
    "Time Zone in Capital": "Indian/Chagos",
    "Currency": "Dollar",
    "Language Codes": "en-IO",
    "Area KM2": 60,
  },
  {
    "name": "British Virgin Islands",
    "iso2": "VG",
    "iso3": "VGB",
    "Top Level Domain": "vg",
    "FIPS": "VI",
    "iso_numeric": "092",
    "GeoNameID": 3577718,
    "E164": 1,
    "phone_code": "1-284",
    "continent": "North America",
    "Capital": "Road Town",
    "Time Zone in Capital": "America/Port_of_Spain",
    "Currency": "Dollar",
    "Language Codes": "en-VG",
    "Area KM2": 153,
  },
  {
    "name": "Brunei",
    "iso2": "BN",
    "iso3": "BRN",
    "Top Level Domain": "bn",
    "FIPS": "BX",
    "iso_numeric": "096",
    "GeoNameID": 1820814,
    "E164": 673,
    "phone_code": 673,
    "continent": "Asia",
    "Capital": "Bandar Seri Begawan",
    "Time Zone in Capital": "Asia/Brunei",
    "Currency": "Dollar",
    "Language Codes": "ms-BN,en-BN",
    "Area KM2": 5770,
  },
  {
    "name": "Bulgaria",
    "iso2": "BG",
    "iso3": "BGR",
    "Top Level Domain": "bg",
    "FIPS": "BU",
    "iso_numeric": 100,
    "GeoNameID": 732800,
    "E164": 359,
    "phone_code": 359,
    "continent": "Europe",
    "Capital": "Sofia",
    "Time Zone in Capital": "Europe/Sofia",
    "Currency": "Lev",
    "Language Codes": "bg,tr-BG",
    "Area KM2": 110910,
  },
  {
    "name": "Burkina Faso",
    "iso2": "BF",
    "iso3": "BFA",
    "Top Level Domain": "bf",
    "FIPS": "UV",
    "iso_numeric": 854,
    "GeoNameID": 2361809,
    "E164": 226,
    "phone_code": 226,
    "continent": "Africa",
    "Capital": "Ouagadougou",
    "Time Zone in Capital": "Africa/Abidjan",
    "Currency": "Franc",
    "Language Codes": "fr-BF",
    "Area KM2": 274200,
  },
  {
    "name": "Burundi",
    "iso2": "BI",
    "iso3": "BDI",
    "Top Level Domain": "bi",
    "FIPS": "BY",
    "iso_numeric": 108,
    "GeoNameID": 433561,
    "E164": 257,
    "phone_code": 257,
    "continent": "Africa",
    "Capital": "Bujumbura",
    "Time Zone in Capital": "Africa/Maputo",
    "Currency": "Franc",
    "Language Codes": "fr-BI,rn",
    "Area KM2": 27830,
  },
  {
    "name": "Cambodia",
    "iso2": "KH",
    "iso3": "KHM",
    "Top Level Domain": "kh",
    "FIPS": "CB",
    "iso_numeric": 116,
    "GeoNameID": 1831722,
    "E164": 855,
    "phone_code": 855,
    "continent": "Asia",
    "Capital": "Phnom Penh",
    "Time Zone in Capital": "Asia/Phnom_Penh",
    "Currency": "Riels",
    "Language Codes": "km,fr,en",
    "Area KM2": 181040,
  },
  {
    "name": "Cameroon",
    "iso2": "CM",
    "iso3": "CMR",
    "Top Level Domain": "cm",
    "FIPS": "CM",
    "iso_numeric": 120,
    "GeoNameID": 2233387,
    "E164": 237,
    "phone_code": 237,
    "continent": "Africa",
    "Capital": "Yaounde",
    "Time Zone in Capital": "Africa/Lagos",
    "Currency": "Franc",
    "Language Codes": "en-CM,fr-CM",
    "Area KM2": 475440,
  },
  {
    "name": "Canada",
    "iso2": "CA",
    "iso3": "CAN",
    "Top Level Domain": "ca",
    "FIPS": "CA",
    "iso_numeric": 124,
    "GeoNameID": 6251999,
    "E164": 1,
    "phone_code": 1,
    "continent": "North America",
    "Capital": "Ottawa",
    "Time Zone in Capital": "America/Toronto",
    "Currency": "Dollar",
    "Language Codes": "en-CA,fr-CA,iu",
    "Area KM2": 9984670,
  },
  {
    "name": "Cape Verde",
    "iso2": "CV",
    "iso3": "CPV",
    "Top Level Domain": "cv",
    "FIPS": "CV",
    "iso_numeric": 132,
    "GeoNameID": 3374766,
    "E164": 238,
    "phone_code": 238,
    "continent": "Africa",
    "Capital": "Praia",
    "Time Zone in Capital": "Atlantic/Cape_Verde",
    "Currency": "Escudo",
    "Language Codes": "pt-CV",
    "Area KM2": 4033,
  },
  {
    "name": "Cayman Islands",
    "iso2": "KY",
    "iso3": "CYM",
    "Top Level Domain": "ky",
    "FIPS": "CJ",
    "iso_numeric": 136,
    "GeoNameID": 3580718,
    "E164": 1,
    "phone_code": "1-345",
    "continent": "North America",
    "Capital": "George Town",
    "Time Zone in Capital": "America/Cayman",
    "Currency": "Dollar",
    "Language Codes": "en-KY",
    "Area KM2": 262,
  },
  {
    "name": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "Top Level Domain": "cf",
    "FIPS": "CT",
    "iso_numeric": 140,
    "GeoNameID": 239880,
    "E164": 236,
    "phone_code": 236,
    "continent": "Africa",
    "Capital": "Bangui",
    "Time Zone in Capital": "Africa/Lagos",
    "Currency": "Franc",
    "Language Codes": "fr-CF,sg,ln,kg",
    "Area KM2": 622984,
  },
  {
    "name": "Chad",
    "iso2": "TD",
    "iso3": "TCD",
    "Top Level Domain": "td",
    "FIPS": "CD",
    "iso_numeric": 148,
    "GeoNameID": 2434508,
    "E164": 235,
    "phone_code": 235,
    "continent": "Africa",
    "Capital": "N'Djamena",
    "Time Zone in Capital": "Africa/Ndjamena",
    "Currency": "Franc",
    "Language Codes": "fr-TD,ar-TD,sre",
    "Area KM2": 1284000,
  },
  {
    "name": "Chile",
    "iso2": "CL",
    "iso3": "CHL",
    "Top Level Domain": "cl",
    "FIPS": "CI",
    "iso_numeric": 152,
    "GeoNameID": 3895114,
    "E164": 56,
    "phone_code": 56,
    "continent": "South America",
    "Capital": "Santiago",
    "Time Zone in Capital": "America/Santiago",
    "Currency": "Peso",
    "Language Codes": "es-CL",
    "Area KM2": 756950,
  },
  {
    "name": "China",
    "iso2": "CN",
    "iso3": "CHN",
    "Top Level Domain": "cn",
    "FIPS": "CH",
    "iso_numeric": 156,
    "GeoNameID": 1814991,
    "E164": 86,
    "phone_code": 86,
    "continent": "Asia",
    "Capital": "Beijing",
    "Time Zone in Capital": "Asia/Shanghai",
    "Currency": "Yuan Renminbi",
    "Language Codes": "zh-CN,yue,wuu,dta,ug,za",
    "Area KM2": 9596960,
  },
  {
    "name": "Christmas Island",
    "iso2": "CX",
    "iso3": "CXR",
    "Top Level Domain": "cx",
    "FIPS": "KT",
    "iso_numeric": 162,
    "GeoNameID": 2078138,
    "E164": 61,
    "phone_code": 61,
    "continent": "Asia",
    "Capital": "Flying Fish Cove",
    "Time Zone in Capital": "Indian/Christmas",
    "Currency": "Dollar",
    "Language Codes": "en,zh,ms-CC",
    "Area KM2": 135,
  },
  {
    "name": "Cocos Islands",
    "iso2": "CC",
    "iso3": "CCK",
    "Top Level Domain": "cc",
    "FIPS": "CK",
    "iso_numeric": 166,
    "GeoNameID": 1547376,
    "E164": 61,
    "phone_code": 61,
    "continent": "Asia",
    "Capital": "West Island",
    "Time Zone in Capital": "Indian/Cocos",
    "Currency": "Dollar",
    "Language Codes": "ms-CC,en",
    "Area KM2": 14,
  },
  {
    "name": "Colombia",
    "iso2": "CO",
    "iso3": "COL",
    "Top Level Domain": "co",
    "FIPS": "CO",
    "iso_numeric": 170,
    "GeoNameID": 3686110,
    "E164": 57,
    "phone_code": 57,
    "continent": "South America",
    "Capital": "Bogota",
    "Time Zone in Capital": "America/Bogota",
    "Currency": "Peso",
    "Language Codes": "es-CO",
    "Area KM2": 1138910,
  },
  {
    "name": "Comoros",
    "iso2": "KM",
    "iso3": "COM",
    "Top Level Domain": "km",
    "FIPS": "CN",
    "iso_numeric": 174,
    "GeoNameID": 921929,
    "E164": 269,
    "phone_code": 269,
    "continent": "Africa",
    "Capital": "Moroni",
    "Time Zone in Capital": "Indian/Comoro",
    "Currency": "Franc",
    "Language Codes": "ar,fr-KM",
    "Area KM2": 2170,
  },
  {
    "name": "Cook Islands",
    "iso2": "CK",
    "iso3": "COK",
    "Top Level Domain": "ck",
    "FIPS": "CW",
    "iso_numeric": 184,
    "GeoNameID": 1899402,
    "E164": 682,
    "phone_code": 682,
    "continent": "Oceania",
    "Capital": "Avarua",
    "Time Zone in Capital": "Pacific/Rarotonga",
    "Currency": "Dollar",
    "Language Codes": "en-CK,mi",
    "Area KM2": 240,
  },
  {
    "name": "Costa Rica",
    "iso2": "CR",
    "iso3": "CRI",
    "Top Level Domain": "cr",
    "FIPS": "CS",
    "iso_numeric": 188,
    "GeoNameID": 3624060,
    "E164": 506,
    "phone_code": 506,
    "continent": "North America",
    "Capital": "San Jose",
    "Time Zone in Capital": "America/Costa_Rica",
    "Currency": "Colon",
    "Language Codes": "es-CR,en",
    "Area KM2": 51100,
  },
  {
    "name": "Croatia",
    "iso2": "HR",
    "iso3": "HRV",
    "Top Level Domain": "hr",
    "FIPS": "HR",
    "iso_numeric": 191,
    "GeoNameID": 3202326,
    "E164": 385,
    "phone_code": 385,
    "continent": "Europe",
    "Capital": "Zagreb",
    "Time Zone in Capital": "Europe/Belgrade",
    "Currency": "Kuna",
    "Language Codes": "hr-HR,sr",
    "Area KM2": 56542,
  },
  {
    "name": "Cuba",
    "iso2": "CU",
    "iso3": "CUB",
    "Top Level Domain": "cu",
    "FIPS": "CU",
    "iso_numeric": 192,
    "GeoNameID": 3562981,
    "E164": 53,
    "phone_code": 53,
    "continent": "North America",
    "Capital": "Havana",
    "Time Zone in Capital": "America/Havana",
    "Currency": "Peso",
    "Language Codes": "es-CU",
    "Area KM2": 110860,
  },
  {
    "name": "Curacao",
    "iso2": "CW",
    "iso3": "CUW",
    "Top Level Domain": "cw",
    "FIPS": "UC",
    "iso_numeric": 531,
    "GeoNameID": 7626836,
    "E164": 599,
    "phone_code": 599,
    "continent": "North America",
    "Capital": "Willemstad",
    "Time Zone in Capital": "America/Curacao",
    "Currency": "Guilder",
    "Language Codes": "nl,pap",
    "Area KM2": 444,
  },
  {
    "name": "Cyprus",
    "iso2": "CY",
    "iso3": "CYP",
    "Top Level Domain": "cy",
    "FIPS": "CY",
    "iso_numeric": 196,
    "GeoNameID": 146669,
    "E164": 357,
    "phone_code": 357,
    "continent": "Europe",
    "Capital": "Nicosia",
    "Time Zone in Capital": "Asia/Nicosia",
    "Currency": "Euro",
    "Language Codes": "el-CY,tr-CY,en",
    "Area KM2": 9250,
  },
  {
    "name": "Czech Republic",
    "iso2": "CZ",
    "iso3": "CZE",
    "Top Level Domain": "cz",
    "FIPS": "EZ",
    "iso_numeric": 203,
    "GeoNameID": 3077311,
    "E164": 420,
    "phone_code": 420,
    "continent": "Europe",
    "Capital": "Prague",
    "Time Zone in Capital": "Europe/Prague",
    "Currency": "Koruna",
    "Language Codes": "cs,sk",
    "Area KM2": 78866,
  },
  {
    "name": "Democratic Republic of the Congo",
    "iso2": "CD",
    "iso3": "COD",
    "Top Level Domain": "cd",
    "FIPS": "CG",
    "iso_numeric": 180,
    "GeoNameID": 203312,
    "E164": 243,
    "phone_code": 243,
    "continent": "Africa",
    "Capital": "Kinshasa",
    "Time Zone in Capital": "Africa/Lagos",
    "Currency": "Franc",
    "Language Codes": "fr-CD,ln,kg",
    "Area KM2": 2345410,
  },
  {
    "name": "Denmark",
    "iso2": "DK",
    "iso3": "DNK",
    "Top Level Domain": "dk",
    "FIPS": "DA",
    "iso_numeric": 208,
    "GeoNameID": 2623032,
    "E164": 45,
    "phone_code": 45,
    "continent": "Europe",
    "Capital": "Copenhagen",
    "Time Zone in Capital": "Europe/Copenhagen",
    "Currency": "Krone",
    "Language Codes": "da-DK,en,fo,de-DK",
    "Area KM2": 43094,
  },
  {
    "name": "Djibouti",
    "iso2": "DJ",
    "iso3": "DJI",
    "Top Level Domain": "dj",
    "FIPS": "DJ",
    "iso_numeric": 262,
    "GeoNameID": 223816,
    "E164": 253,
    "phone_code": 253,
    "continent": "Africa",
    "Capital": "Djibouti",
    "Time Zone in Capital": "Africa/Djibouti",
    "Currency": "Franc",
    "Language Codes": "fr-DJ,ar,so-DJ,aa",
    "Area KM2": 23000,
  },
  {
    "name": "Dominica",
    "iso2": "DM",
    "iso3": "DMA",
    "Top Level Domain": "dm",
    "FIPS": "DO",
    "iso_numeric": 212,
    "GeoNameID": 3575830,
    "E164": 1,
    "phone_code": "1-767",
    "continent": "North America",
    "Capital": "Roseau",
    "Time Zone in Capital": "America/Port_of_Spain",
    "Currency": "Dollar",
    "Language Codes": "en-DM",
    "Area KM2": 754,
  },
  {
    "name": "Dominican Republic",
    "iso2": "DO",
    "iso3": "DOM",
    "Top Level Domain": "do",
    "FIPS": "DR",
    "iso_numeric": 214,
    "GeoNameID": 3508796,
    "E164": 1,
    "phone_code": "1-809, 1-829, 1-849",
    "continent": "North America",
    "Capital": "Santo Domingo",
    "Time Zone in Capital": "America/Santo_Domingo",
    "Currency": "Peso",
    "Language Codes": "es-DO",
    "Area KM2": 48730,
  },
  {
    "name": "East Timor",
    "iso2": "TL",
    "iso3": "TLS",
    "Top Level Domain": "tl",
    "FIPS": "TT",
    "iso_numeric": 626,
    "GeoNameID": 1966436,
    "E164": 670,
    "phone_code": 670,
    "continent": "Oceania",
    "Capital": "Dili",
    "Time Zone in Capital": "Asia/Dili",
    "Currency": "Dollar",
    "Language Codes": "tet,pt-TL,id,en",
    "Area KM2": 15007,
  },
  {
    "name": "Ecuador",
    "iso2": "EC",
    "iso3": "ECU",
    "Top Level Domain": "ec",
    "FIPS": "EC",
    "iso_numeric": 218,
    "GeoNameID": 3658394,
    "E164": 593,
    "phone_code": 593,
    "continent": "South America",
    "Capital": "Quito",
    "Time Zone in Capital": "America/Guayaquil",
    "Currency": "Dollar",
    "Language Codes": "es-EC",
    "Area KM2": 283560,
  },
  {
    "name": "Egypt",
    "iso2": "EG",
    "iso3": "EGY",
    "Top Level Domain": "eg",
    "FIPS": "EG",
    "iso_numeric": 818,
    "GeoNameID": 357994,
    "E164": 20,
    "phone_code": 20,
    "continent": "Africa",
    "Capital": "Cairo",
    "Time Zone in Capital": "Africa/Cairo",
    "Currency": "Pound",
    "Language Codes": "ar-EG,en,fr",
    "Area KM2": 1001450,
  },
  {
    "name": "El Salvador",
    "iso2": "SV",
    "iso3": "SLV",
    "Top Level Domain": "sv",
    "FIPS": "ES",
    "iso_numeric": 222,
    "GeoNameID": 3585968,
    "E164": 503,
    "phone_code": 503,
    "continent": "North America",
    "Capital": "San Salvador",
    "Time Zone in Capital": "America/El_Salvador",
    "Currency": "Dollar",
    "Language Codes": "es-SV",
    "Area KM2": 21040,
  },
  {
    "name": "Equatorial Guinea",
    "iso2": "GQ",
    "iso3": "GNQ",
    "Top Level Domain": "gq",
    "FIPS": "EK",
    "iso_numeric": 226,
    "GeoNameID": 2309096,
    "E164": 240,
    "phone_code": 240,
    "continent": "Africa",
    "Capital": "Malabo",
    "Time Zone in Capital": "Africa/Lagos",
    "Currency": "Franc",
    "Language Codes": "es-GQ,fr",
    "Area KM2": 28051,
  },
  {
    "name": "Eritrea",
    "iso2": "ER",
    "iso3": "ERI",
    "Top Level Domain": "er",
    "FIPS": "ER",
    "iso_numeric": 232,
    "GeoNameID": 338010,
    "E164": 291,
    "phone_code": 291,
    "continent": "Africa",
    "Capital": "Asmara",
    "Time Zone in Capital": "Africa/Asmara",
    "Currency": "Nakfa",
    "Language Codes": "aa-ER,ar,tig,kun,ti-ER",
    "Area KM2": 121320,
  },
  {
    "name": "Estonia",
    "iso2": "EE",
    "iso3": "EST",
    "Top Level Domain": "ee",
    "FIPS": "EN",
    "iso_numeric": 233,
    "GeoNameID": 453733,
    "E164": 372,
    "phone_code": 372,
    "continent": "Europe",
    "Capital": "Tallinn",
    "Time Zone in Capital": "Europe/Tallinn",
    "Currency": "Euro",
    "Language Codes": "et,ru",
    "Area KM2": 45226,
  },
  {
    "name": "Ethiopia",
    "iso2": "ET",
    "iso3": "ETH",
    "Top Level Domain": "et",
    "FIPS": "ET",
    "iso_numeric": 231,
    "GeoNameID": 337996,
    "E164": 251,
    "phone_code": 251,
    "continent": "Africa",
    "Capital": "Addis Ababa",
    "Time Zone in Capital": "Africa/Addis_Ababa",
    "Currency": "Birr",
    "Language Codes": "am,en-ET,om-ET,ti-ET,so-ET,sid",
    "Area KM2": 1127127,
  },
  {
    "name": "Falkland Islands",
    "iso2": "FK",
    "iso3": "FLK",
    "Top Level Domain": "fk",
    "FIPS": "FK",
    "iso_numeric": 238,
    "GeoNameID": 3474414,
    "E164": 500,
    "phone_code": 500,
    "continent": "South America",
    "Capital": "Stanley",
    "Time Zone in Capital": "Atlantic/Stanley",
    "Currency": "Pound",
    "Language Codes": "en-FK",
    "Area KM2": 12173,
  },
  {
    "name": "Faroe Islands",
    "iso2": "FO",
    "iso3": "FRO",
    "Top Level Domain": "fo",
    "FIPS": "FO",
    "iso_numeric": 234,
    "GeoNameID": 2622320,
    "E164": 298,
    "phone_code": 298,
    "continent": "Europe",
    "Capital": "Torshavn",
    "Time Zone in Capital": "Atlantic/Faroe",
    "Currency": "Krone",
    "Language Codes": "fo,da-FO",
    "Area KM2": 1399,
  },
  {
    "name": "Fiji",
    "iso2": "FJ",
    "iso3": "FJI",
    "Top Level Domain": "fj",
    "FIPS": "FJ",
    "iso_numeric": 242,
    "GeoNameID": 2205218,
    "E164": 679,
    "phone_code": 679,
    "continent": "Oceania",
    "Capital": "Suva",
    "Time Zone in Capital": "Pacific/Fiji",
    "Currency": "Dollar",
    "Language Codes": "en-FJ,fj",
    "Area KM2": 18270,
  },
  {
    "name": "Finland",
    "iso2": "FI",
    "iso3": "FIN",
    "Top Level Domain": "fi",
    "FIPS": "FI",
    "iso_numeric": 246,
    "GeoNameID": 660013,
    "E164": 358,
    "phone_code": 358,
    "continent": "Europe",
    "Capital": "Helsinki",
    "Time Zone in Capital": "Europe/Helsinki",
    "Currency": "Euro",
    "Language Codes": "fi-FI,sv-FI,smn",
    "Area KM2": 337030,
  },
  {
    "name": "France",
    "iso2": "FR",
    "iso3": "FRA",
    "Top Level Domain": "fr",
    "FIPS": "FR",
    "iso_numeric": 250,
    "GeoNameID": 3017382,
    "E164": 33,
    "phone_code": 33,
    "continent": "Europe",
    "Capital": "Paris",
    "Time Zone in Capital": "Europe/Paris",
    "Currency": "Euro",
    "Language Codes": "fr-FR,frp,br,co,ca,eu,oc",
    "Area KM2": 547030,
  },
  {
    "name": "French Polynesia",
    "iso2": "PF",
    "iso3": "PYF",
    "Top Level Domain": "pf",
    "FIPS": "FP",
    "iso_numeric": 258,
    "GeoNameID": 4030656,
    "E164": 689,
    "phone_code": 689,
    "continent": "Oceania",
    "Capital": "Papeete",
    "Time Zone in Capital": "Pacific/Tahiti",
    "Currency": "Franc",
    "Language Codes": "fr-PF,ty",
    "Area KM2": 4167,
  },
  {
    "name": "Gabon",
    "iso2": "GA",
    "iso3": "GAB",
    "Top Level Domain": "ga",
    "FIPS": "GB",
    "iso_numeric": 266,
    "GeoNameID": 2400553,
    "E164": 241,
    "phone_code": 241,
    "continent": "Africa",
    "Capital": "Libreville",
    "Time Zone in Capital": "Africa/Lagos",
    "Currency": "Franc",
    "Language Codes": "fr-GA",
    "Area KM2": 267667,
  },
  {
    "name": "Gambia",
    "iso2": "GM",
    "iso3": "GMB",
    "Top Level Domain": "gm",
    "FIPS": "GA",
    "iso_numeric": 270,
    "GeoNameID": 2413451,
    "E164": 220,
    "phone_code": 220,
    "continent": "Africa",
    "Capital": "Banjul",
    "Time Zone in Capital": "Africa/Abidjan",
    "Currency": "Dalasi",
    "Language Codes": "en-GM,mnk,wof,wo,ff",
    "Area KM2": 11300,
  },
  {
    "name": "Georgia",
    "iso2": "GE",
    "iso3": "GEO",
    "Top Level Domain": "ge",
    "FIPS": "GG",
    "iso_numeric": 268,
    "GeoNameID": 614540,
    "E164": 995,
    "phone_code": 995,
    "continent": "Asia",
    "Capital": "Tbilisi",
    "Time Zone in Capital": "Asia/Tbilisi",
    "Currency": "Lari",
    "Language Codes": "ka,ru,hy,az",
    "Area KM2": 69700,
  },
  {
    "name": "Germany",
    "iso2": "DE",
    "iso3": "DEU",
    "Top Level Domain": "de",
    "FIPS": "GM",
    "iso_numeric": 276,
    "GeoNameID": 2921044,
    "E164": 49,
    "phone_code": 49,
    "continent": "Europe",
    "Capital": "Berlin",
    "Time Zone in Capital": "Europe/Berlin",
    "Currency": "Euro",
    "Language Codes": "de",
    "Area KM2": 357021,
  },
  {
    "name": "Ghana",
    "iso2": "GH",
    "iso3": "GHA",
    "Top Level Domain": "gh",
    "FIPS": "GH",
    "iso_numeric": 288,
    "GeoNameID": 2300660,
    "E164": 233,
    "phone_code": 233,
    "continent": "Africa",
    "Capital": "Accra",
    "Time Zone in Capital": "Africa/Accra",
    "Currency": "Cedi",
    "Language Codes": "en-GH,ak,ee,tw",
    "Area KM2": 239460,
  },
  {
    "name": "Gibraltar",
    "iso2": "GI",
    "iso3": "GIB",
    "Top Level Domain": "gi",
    "FIPS": "GI",
    "iso_numeric": 292,
    "GeoNameID": 2411586,
    "E164": 350,
    "phone_code": 350,
    "continent": "Europe",
    "Capital": "Gibraltar",
    "Time Zone in Capital": "Europe/Gibraltar",
    "Currency": "Pound",
    "Language Codes": "en-GI,es,it,pt",
    "Area KM2": 7,
  },
  {
    "name": "Greece",
    "iso2": "GR",
    "iso3": "GRC",
    "Top Level Domain": "gr",
    "FIPS": "GR",
    "iso_numeric": 300,
    "GeoNameID": 390903,
    "E164": 30,
    "phone_code": 30,
    "continent": "Europe",
    "Capital": "Athens",
    "Time Zone in Capital": "Europe/Athens",
    "Currency": "Euro",
    "Language Codes": "el-GR,en,fr",
    "Area KM2": 131940,
  },
  {
    "name": "Greenland",
    "iso2": "GL",
    "iso3": "GRL",
    "Top Level Domain": "gl",
    "FIPS": "GL",
    "iso_numeric": 304,
    "GeoNameID": 3425505,
    "E164": 299,
    "phone_code": 299,
    "continent": "North America",
    "Capital": "Nuuk",
    "Time Zone in Capital": "America/Godthab",
    "Currency": "Krone",
    "Language Codes": "kl,da-GL,en",
    "Area KM2": 2166086,
  },
  {
    "name": "Grenada",
    "iso2": "GD",
    "iso3": "GRD",
    "Top Level Domain": "gd",
    "FIPS": "GJ",
    "iso_numeric": 308,
    "GeoNameID": 3580239,
    "E164": 1,
    "phone_code": "1-473",
    "continent": "North America",
    "Capital": "St. George's",
    "Time Zone in Capital": "America/Port_of_Spain",
    "Currency": "Dollar",
    "Language Codes": "en-GD",
    "Area KM2": 344,
  },
  {
    "name": "Guam",
    "iso2": "GU",
    "iso3": "GUM",
    "Top Level Domain": "gu",
    "FIPS": "GQ",
    "iso_numeric": 316,
    "GeoNameID": 4043988,
    "E164": 1,
    "phone_code": "1-671",
    "continent": "Oceania",
    "Capital": "Hagatna",
    "Time Zone in Capital": "Pacific/Guam",
    "Currency": "Dollar",
    "Language Codes": "en-GU,ch-GU",
    "Area KM2": 549,
  },
  {
    "name": "Guatemala",
    "iso2": "GT",
    "iso3": "GTM",
    "Top Level Domain": "gt",
    "FIPS": "GT",
    "iso_numeric": 320,
    "GeoNameID": 3595528,
    "E164": 502,
    "phone_code": 502,
    "continent": "North America",
    "Capital": "Guatemala City",
    "Time Zone in Capital": "America/Guatemala",
    "Currency": "Quetzal",
    "Language Codes": "es-GT",
    "Area KM2": 108890,
  },
  {
    "name": "Guernsey",
    "iso2": "GG",
    "iso3": "GGY",
    "Top Level Domain": "gg",
    "FIPS": "GK",
    "iso_numeric": 831,
    "GeoNameID": 3042362,
    "E164": 44,
    "phone_code": "44-1481",
    "continent": "Europe",
    "Capital": "St Peter Port",
    "Time Zone in Capital": "Europe/London",
    "Currency": "Pound",
    "Language Codes": "en,fr",
    "Area KM2": 78,
  },
  {
    "name": "Guinea",
    "iso2": "GN",
    "iso3": "GIN",
    "Top Level Domain": "gn",
    "FIPS": "GV",
    "iso_numeric": 324,
    "GeoNameID": 2420477,
    "E164": 224,
    "phone_code": 224,
    "continent": "Africa",
    "Capital": "Conakry",
    "Time Zone in Capital": "Africa/Abidjan",
    "Currency": "Franc",
    "Language Codes": "fr-GN",
    "Area KM2": 245857,
  },
  {
    "name": "Guinea-Bissau",
    "iso2": "GW",
    "iso3": "GNB",
    "Top Level Domain": "gw",
    "FIPS": "PU",
    "iso_numeric": 624,
    "GeoNameID": 2372248,
    "E164": 245,
    "phone_code": 245,
    "continent": "Africa",
    "Capital": "Bissau",
    "Time Zone in Capital": "Africa/Bissau",
    "Currency": "Franc",
    "Language Codes": "pt-GW,pov",
    "Area KM2": 36120,
  },
  {
    "name": "Guyana",
    "iso2": "GY",
    "iso3": "GUY",
    "Top Level Domain": "gy",
    "FIPS": "GY",
    "iso_numeric": 328,
    "GeoNameID": 3378535,
    "E164": 592,
    "phone_code": 592,
    "continent": "South America",
    "Capital": "Georgetown",
    "Time Zone in Capital": "America/Guyana",
    "Currency": "Dollar",
    "Language Codes": "en-GY",
    "Area KM2": 214970,
  },
  {
    "name": "Haiti",
    "iso2": "HT",
    "iso3": "HTI",
    "Top Level Domain": "ht",
    "FIPS": "HA",
    "iso_numeric": 332,
    "GeoNameID": 3723988,
    "E164": 509,
    "phone_code": 509,
    "continent": "North America",
    "Capital": "Port-au-Prince",
    "Time Zone in Capital": "America/Port-au-Prince",
    "Currency": "Gourde",
    "Language Codes": "ht,fr-HT",
    "Area KM2": 27750,
  },
  {
    "name": "Honduras",
    "iso2": "HN",
    "iso3": "HND",
    "Top Level Domain": "hn",
    "FIPS": "HO",
    "iso_numeric": 340,
    "GeoNameID": 3608932,
    "E164": 504,
    "phone_code": 504,
    "continent": "North America",
    "Capital": "Tegucigalpa",
    "Time Zone in Capital": "America/Tegucigalpa",
    "Currency": "Lempira",
    "Language Codes": "es-HN",
    "Area KM2": 112090,
  },
  {
    "name": "Hong Kong",
    "iso2": "HK",
    "iso3": "HKG",
    "Top Level Domain": "hk",
    "FIPS": "HK",
    "iso_numeric": 344,
    "GeoNameID": 1819730,
    "E164": 852,
    "phone_code": 852,
    "continent": "Asia",
    "Capital": "Hong Kong",
    "Time Zone in Capital": "Asia/Hong_Kong",
    "Currency": "Dollar",
    "Language Codes": "zh-HK,yue,zh,en",
    "Area KM2": 1092,
  },
  {
    "name": "Hungary",
    "iso2": "HU",
    "iso3": "HUN",
    "Top Level Domain": "hu",
    "FIPS": "HU",
    "iso_numeric": 348,
    "GeoNameID": 719819,
    "E164": 36,
    "phone_code": 36,
    "continent": "Europe",
    "Capital": "Budapest",
    "Time Zone in Capital": "Europe/Budapest",
    "Currency": "Forint",
    "Language Codes": "hu-HU",
    "Area KM2": 93030,
  },
  {
    "name": "Iceland",
    "iso2": "IS",
    "iso3": "ISL",
    "Top Level Domain": "is",
    "FIPS": "IC",
    "iso_numeric": 352,
    "GeoNameID": 2629691,
    "E164": 354,
    "phone_code": 354,
    "continent": "Europe",
    "Capital": "Reykjavik",
    "Time Zone in Capital": "Atlantic/Reykjavik",
    "Currency": "Krona",
    "Language Codes": "is,en,de,da,sv,no",
    "Area KM2": 103000,
  },
  {
    "name": "India",
    "iso2": "IN",
    "iso3": "IND",
    "Top Level Domain": "in",
    "FIPS": "IN",
    "iso_numeric": 356,
    "GeoNameID": 1269750,
    "E164": 91,
    "phone_code": 91,
    "continent": "Asia",
    "Capital": "New Delhi",
    "Time Zone in Capital": "Asia/Kolkata",
    "Currency": "Rupee",
    "Language Codes": "en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,sat,ks,ne,sd,kok,doi,mni,sit,sa,fr,lus,inc",
    "Area KM2": 3287590,
  },
  {
    "name": "Indonesia",
    "iso2": "ID",
    "iso3": "IDN",
    "Top Level Domain": "id",
    "FIPS": "ID",
    "iso_numeric": 360,
    "GeoNameID": 1643084,
    "E164": 62,
    "phone_code": 62,
    "continent": "Asia",
    "Capital": "Jakarta",
    "Time Zone in Capital": "Asia/Jakarta",
    "Currency": "Rupiah",
    "Language Codes": "id,en,nl,jv",
    "Area KM2": 1919440,
  },
  {
    "name": "Iran",
    "iso2": "IR",
    "iso3": "IRN",
    "Top Level Domain": "ir",
    "FIPS": "IR",
    "iso_numeric": 364,
    "GeoNameID": 130758,
    "E164": 98,
    "phone_code": 98,
    "continent": "Asia",
    "Capital": "Tehran",
    "Time Zone in Capital": "Asia/Tehran",
    "Currency": "Rial",
    "Language Codes": "fa-IR,ku",
    "Area KM2": 1648000,
  },
  {
    "name": "Iraq",
    "iso2": "IQ",
    "iso3": "IRQ",
    "Top Level Domain": "iq",
    "FIPS": "IZ",
    "iso_numeric": 368,
    "GeoNameID": 99237,
    "E164": 964,
    "phone_code": 964,
    "continent": "Asia",
    "Capital": "Baghdad",
    "Time Zone in Capital": "Asia/Baghdad",
    "Currency": "Dinar",
    "Language Codes": "ar-IQ,ku,hy",
    "Area KM2": 437072,
  },
  {
    "name": "Ireland",
    "iso2": "IE",
    "iso3": "IRL",
    "Top Level Domain": "ie",
    "FIPS": "EI",
    "iso_numeric": 372,
    "GeoNameID": 2963597,
    "E164": 353,
    "phone_code": 353,
    "continent": "Europe",
    "Capital": "Dublin",
    "Time Zone in Capital": "Europe/Dublin",
    "Currency": "Euro",
    "Language Codes": "en-IE,ga-IE",
    "Area KM2": 70280,
  },
  {
    "name": "Isle of Man",
    "iso2": "IM",
    "iso3": "IMN",
    "Top Level Domain": "im",
    "FIPS": "IM",
    "iso_numeric": 833,
    "GeoNameID": 3042225,
    "E164": 44,
    "phone_code": "44-1624",
    "continent": "Europe",
    "Capital": "Douglas, Isle of Man",
    "Time Zone in Capital": "Europe/London",
    "Currency": "Pound",
    "Language Codes": "en,gv",
    "Area KM2": 572,
  },
  {
    "name": "Israel",
    "iso2": "IL",
    "iso3": "ISR",
    "Top Level Domain": "il",
    "FIPS": "IS",
    "iso_numeric": 376,
    "GeoNameID": 294640,
    "E164": 972,
    "phone_code": 972,
    "continent": "Asia",
    "Capital": "Jerusalem",
    "Time Zone in Capital": "Asia/Jerusalem",
    "Currency": "Shekel",
    "Language Codes": "he,ar-IL,en-IL,",
    "Area KM2": 20770,
  },
  {
    "name": "Italy",
    "iso2": "IT",
    "iso3": "ITA",
    "Top Level Domain": "it",
    "FIPS": "IT",
    "iso_numeric": 380,
    "GeoNameID": 3175395,
    "E164": 39,
    "phone_code": 39,
    "continent": "Europe",
    "Capital": "Rome",
    "Time Zone in Capital": "Europe/Rome",
    "Currency": "Euro",
    "Language Codes": "it-IT,de-IT,fr-IT,sc,ca,co,sl",
    "Area KM2": 301230,
  },
  {
    "name": "Ivory Coast",
    "iso2": "CI",
    "iso3": "CIV",
    "Top Level Domain": "ci",
    "FIPS": "IV",
    "iso_numeric": 384,
    "GeoNameID": 2287781,
    "E164": 225,
    "phone_code": 225,
    "continent": "Africa",
    "Capital": "Yamoussoukro",
    "Time Zone in Capital": "Africa/Abidjan",
    "Currency": "Franc",
    "Language Codes": "fr-CI",
    "Area KM2": 322460,
  },
  {
    "name": "Jamaica",
    "iso2": "JM",
    "iso3": "JAM",
    "Top Level Domain": "jm",
    "FIPS": "JM",
    "iso_numeric": 388,
    "GeoNameID": 3489940,
    "E164": 1,
    "phone_code": "1-876",
    "continent": "North America",
    "Capital": "Kingston",
    "Time Zone in Capital": "America/Jamaica",
    "Currency": "Dollar",
    "Language Codes": "en-JM",
    "Area KM2": 10991,
  },
  {
    "name": "Japan",
    "iso2": "JP",
    "iso3": "JPN",
    "Top Level Domain": "jp",
    "FIPS": "JA",
    "iso_numeric": 392,
    "GeoNameID": 1861060,
    "E164": 81,
    "phone_code": 81,
    "continent": "Asia",
    "Capital": "Tokyo",
    "Time Zone in Capital": "Asia/Tokyo",
    "Currency": "Yen",
    "Language Codes": "ja",
    "Area KM2": 377835,
  },
  {
    "name": "Jersey",
    "iso2": "JE",
    "iso3": "JEY",
    "Top Level Domain": "je",
    "FIPS": "JE",
    "iso_numeric": 832,
    "GeoNameID": 3042142,
    "E164": 44,
    "phone_code": "44-1534",
    "continent": "Europe",
    "Capital": "Saint Helier",
    "Time Zone in Capital": "Europe/London",
    "Currency": "Pound",
    "Language Codes": "en,pt",
    "Area KM2": 116,
  },
  {
    "name": "Jordan",
    "iso2": "JO",
    "iso3": "JOR",
    "Top Level Domain": "jo",
    "FIPS": "JO",
    "iso_numeric": 400,
    "GeoNameID": 248816,
    "E164": 962,
    "phone_code": 962,
    "continent": "Asia",
    "Capital": "Amman",
    "Time Zone in Capital": "Asia/Amman",
    "Currency": "Dinar",
    "Language Codes": "ar-JO,en",
    "Area KM2": 92300,
  },
  {
    "name": "Kazakhstan",
    "iso2": "KZ",
    "iso3": "KAZ",
    "Top Level Domain": "kz",
    "FIPS": "KZ",
    "iso_numeric": 398,
    "GeoNameID": 1522867,
    "E164": 7,
    "phone_code": 7,
    "continent": "Asia",
    "Capital": "Astana",
    "Time Zone in Capital": "Asia/Almaty",
    "Currency": "Tenge",
    "Language Codes": "kk,ru",
    "Area KM2": 2717300,
  },
  {
    "name": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "Top Level Domain": "ke",
    "FIPS": "KE",
    "iso_numeric": 404,
    "GeoNameID": 192950,
    "E164": 254,
    "phone_code": 254,
    "continent": "Africa",
    "Capital": "Nairobi",
    "Time Zone in Capital": "Africa/Nairobi",
    "Currency": "Shilling",
    "Language Codes": "en-KE,sw-KE",
    "Area KM2": 582650,
  },
  {
    "name": "Kiribati",
    "iso2": "KI",
    "iso3": "KIR",
    "Top Level Domain": "ki",
    "FIPS": "KR",
    "iso_numeric": 296,
    "GeoNameID": 4030945,
    "E164": 686,
    "phone_code": 686,
    "continent": "Oceania",
    "Capital": "Tarawa",
    "Time Zone in Capital": "Pacific/Tarawa",
    "Currency": "Dollar",
    "Language Codes": "en-KI,gil",
    "Area KM2": 811,
  },
  {
    "name": "Kosovo",
    "iso2": "XK",
    "iso3": "XKX",
    "Top Level Domain": "",
    "FIPS": "KV",
    "iso_numeric": 0,
    "GeoNameID": 831053,
    "E164": 383,
    "phone_code": 383,
    "continent": "Europe",
    "Capital": "Pristina",
    "Time Zone in Capital": "Europe/Belgrade",
    "Currency": "Euro",
    "Language Codes": "sq,sr",
    "Area KM2": 10887,
  },
  {
    "name": "Kuwait",
    "iso2": "KW",
    "iso3": "KWT",
    "Top Level Domain": "kw",
    "FIPS": "KU",
    "iso_numeric": 414,
    "GeoNameID": 285570,
    "E164": 965,
    "phone_code": 965,
    "continent": "Asia",
    "Capital": "Kuwait City",
    "Time Zone in Capital": "Asia/Kuwait",
    "Currency": "Dinar",
    "Language Codes": "ar-KW,en",
    "Area KM2": 17820,
  },
  {
    "name": "Kyrgyzstan",
    "iso2": "KG",
    "iso3": "KGZ",
    "Top Level Domain": "kg",
    "FIPS": "KG",
    "iso_numeric": 417,
    "GeoNameID": 1527747,
    "E164": 996,
    "phone_code": 996,
    "continent": "Asia",
    "Capital": "Bishkek",
    "Time Zone in Capital": "Asia/Bishkek",
    "Currency": "Som",
    "Language Codes": "ky,uz,ru",
    "Area KM2": 198500,
  },
  {
    "name": "Laos",
    "iso2": "LA",
    "iso3": "LAO",
    "Top Level Domain": "la",
    "FIPS": "LA",
    "iso_numeric": 418,
    "GeoNameID": 1655842,
    "E164": 856,
    "phone_code": 856,
    "continent": "Asia",
    "Capital": "Vientiane",
    "Time Zone in Capital": "Asia/Vientiane",
    "Currency": "Kip",
    "Language Codes": "lo,fr,en",
    "Area KM2": 236800,
  },
  {
    "name": "Latvia",
    "iso2": "LV",
    "iso3": "LVA",
    "Top Level Domain": "lv",
    "FIPS": "LG",
    "iso_numeric": 428,
    "GeoNameID": 458258,
    "E164": 371,
    "phone_code": 371,
    "continent": "Europe",
    "Capital": "Riga",
    "Time Zone in Capital": "Europe/Riga",
    "Currency": "Euro",
    "Language Codes": "lv,ru,lt",
    "Area KM2": 64589,
  },
  {
    "name": "Lebanon",
    "iso2": "LB",
    "iso3": "LBN",
    "Top Level Domain": "lb",
    "FIPS": "LE",
    "iso_numeric": 422,
    "GeoNameID": 272103,
    "E164": 961,
    "phone_code": 961,
    "continent": "Asia",
    "Capital": "Beirut",
    "Time Zone in Capital": "Asia/Beirut",
    "Currency": "Pound",
    "Language Codes": "ar-LB,fr-LB,en,hy",
    "Area KM2": 10400,
  },
  {
    "name": "Lesotho",
    "iso2": "LS",
    "iso3": "LSO",
    "Top Level Domain": "ls",
    "FIPS": "LT",
    "iso_numeric": 426,
    "GeoNameID": 932692,
    "E164": 266,
    "phone_code": 266,
    "continent": "Africa",
    "Capital": "Maseru",
    "Time Zone in Capital": "Africa/Johannesburg",
    "Currency": "Loti",
    "Language Codes": "en-LS,st,zu,xh",
    "Area KM2": 30355,
  },
  {
    "name": "Liberia",
    "iso2": "LR",
    "iso3": "LBR",
    "Top Level Domain": "lr",
    "FIPS": "LI",
    "iso_numeric": 430,
    "GeoNameID": 2275384,
    "E164": 231,
    "phone_code": 231,
    "continent": "Africa",
    "Capital": "Monrovia",
    "Time Zone in Capital": "Africa/Monrovia",
    "Currency": "Dollar",
    "Language Codes": "en-LR",
    "Area KM2": 111370,
  },
  {
    "name": "Libya",
    "iso2": "LY",
    "iso3": "LBY",
    "Top Level Domain": "ly",
    "FIPS": "LY",
    "iso_numeric": 434,
    "GeoNameID": 2215636,
    "E164": 218,
    "phone_code": 218,
    "continent": "Africa",
    "Capital": "Tripolis",
    "Time Zone in Capital": "Africa/Tripoli",
    "Currency": "Dinar",
    "Language Codes": "ar-LY,it,en",
    "Area KM2": 1759540,
  },
  {
    "name": "Liechtenstein",
    "iso2": "LI",
    "iso3": "LIE",
    "Top Level Domain": "li",
    "FIPS": "LS",
    "iso_numeric": 438,
    "GeoNameID": 3042058,
    "E164": 423,
    "phone_code": 423,
    "continent": "Europe",
    "Capital": "Vaduz",
    "Time Zone in Capital": "Europe/Zurich",
    "Currency": "Franc",
    "Language Codes": "de-LI",
    "Area KM2": 160,
  },
  {
    "name": "Lithuania",
    "iso2": "LT",
    "iso3": "LTU",
    "Top Level Domain": "lt",
    "FIPS": "LH",
    "iso_numeric": 440,
    "GeoNameID": 597427,
    "E164": 370,
    "phone_code": 370,
    "continent": "Europe",
    "Capital": "Vilnius",
    "Time Zone in Capital": "Europe/Vilnius",
    "Currency": "Euro",
    "Language Codes": "lt,ru,pl",
    "Area KM2": 65200,
  },
  {
    "name": "Luxembourg",
    "iso2": "LU",
    "iso3": "LUX",
    "Top Level Domain": "lu",
    "FIPS": "LU",
    "iso_numeric": 442,
    "GeoNameID": 2960313,
    "E164": 352,
    "phone_code": 352,
    "continent": "Europe",
    "Capital": "Luxembourg",
    "Time Zone in Capital": "Europe/Luxembourg",
    "Currency": "Euro",
    "Language Codes": "lb,de-LU,fr-LU",
    "Area KM2": 2586,
  },
  {
    "name": "Macau",
    "iso2": "MO",
    "iso3": "MAC",
    "Top Level Domain": "mo",
    "FIPS": "MC",
    "iso_numeric": 446,
    "GeoNameID": 1821275,
    "E164": 853,
    "phone_code": 853,
    "continent": "Asia",
    "Capital": "Macao",
    "Time Zone in Capital": "Asia/Macau",
    "Currency": "Pataca",
    "Language Codes": "zh,zh-MO,pt",
    "Area KM2": 254,
  },
  {
    "name": "Macedonia",
    "iso2": "MK",
    "iso3": "MKD",
    "Top Level Domain": "mk",
    "FIPS": "MK",
    "iso_numeric": 807,
    "GeoNameID": 718075,
    "E164": 389,
    "phone_code": 389,
    "continent": "Europe",
    "Capital": "Skopje",
    "Time Zone in Capital": "Europe/Belgrade",
    "Currency": "Denar",
    "Language Codes": "mk,sq,tr,rmm,sr",
    "Area KM2": 25333,
  },
  {
    "name": "Madagascar",
    "iso2": "MG",
    "iso3": "MDG",
    "Top Level Domain": "mg",
    "FIPS": "MA",
    "iso_numeric": 450,
    "GeoNameID": 1062947,
    "E164": 261,
    "phone_code": 261,
    "continent": "Africa",
    "Capital": "Antananarivo",
    "Time Zone in Capital": "Indian/Antananarivo",
    "Currency": "Ariary",
    "Language Codes": "fr-MG,mg",
    "Area KM2": 587040,
  },
  {
    "name": "Malawi",
    "iso2": "MW",
    "iso3": "MWI",
    "Top Level Domain": "mw",
    "FIPS": "MI",
    "iso_numeric": 454,
    "GeoNameID": 927384,
    "E164": 265,
    "phone_code": 265,
    "continent": "Africa",
    "Capital": "Lilongwe",
    "Time Zone in Capital": "Africa/Maputo",
    "Currency": "Kwacha",
    "Language Codes": "ny,yao,tum,swk",
    "Area KM2": 118480,
  },
  {
    "name": "Malaysia",
    "iso2": "MY",
    "iso3": "MYS",
    "Top Level Domain": "my",
    "FIPS": "MY",
    "iso_numeric": 458,
    "GeoNameID": 1733045,
    "E164": 60,
    "phone_code": 60,
    "continent": "Asia",
    "Capital": "Kuala Lumpur",
    "Time Zone in Capital": "Asia/Kuala_Lumpur",
    "Currency": "Ringgit",
    "Language Codes": "ms-MY,en,zh,ta,te,ml,pa,th",
    "Area KM2": 329750,
  },
  {
    "name": "Maldives",
    "iso2": "MV",
    "iso3": "MDV",
    "Top Level Domain": "mv",
    "FIPS": "MV",
    "iso_numeric": 462,
    "GeoNameID": 1282028,
    "E164": 960,
    "phone_code": 960,
    "continent": "Asia",
    "Capital": "Male",
    "Time Zone in Capital": "Indian/Maldives",
    "Currency": "Rufiyaa",
    "Language Codes": "dv,en",
    "Area KM2": 300,
  },
  {
    "name": "Mali",
    "iso2": "ML",
    "iso3": "MLI",
    "Top Level Domain": "ml",
    "FIPS": "ML",
    "iso_numeric": 466,
    "GeoNameID": 2453866,
    "E164": 223,
    "phone_code": 223,
    "continent": "Africa",
    "Capital": "Bamako",
    "Time Zone in Capital": "Africa/Abidjan",
    "Currency": "Franc",
    "Language Codes": "fr-ML,bm",
    "Area KM2": 1240000,
  },
  {
    "name": "Malta",
    "iso2": "MT",
    "iso3": "MLT",
    "Top Level Domain": "mt",
    "FIPS": "MT",
    "iso_numeric": 470,
    "GeoNameID": 2562770,
    "E164": 356,
    "phone_code": 356,
    "continent": "Europe",
    "Capital": "Valletta",
    "Time Zone in Capital": "Europe/Malta",
    "Currency": "Euro",
    "Language Codes": "mt,en-MT",
    "Area KM2": 316,
  },
  {
    "name": "Marshall Islands",
    "iso2": "MH",
    "iso3": "MHL",
    "Top Level Domain": "mh",
    "FIPS": "RM",
    "iso_numeric": 584,
    "GeoNameID": 2080185,
    "E164": 692,
    "phone_code": 692,
    "continent": "Oceania",
    "Capital": "Majuro",
    "Time Zone in Capital": "Pacific/Majuro",
    "Currency": "Dollar",
    "Language Codes": "mh,en-MH",
    "Area KM2": 181,
  },
  {
    "name": "Mauritania",
    "iso2": "MR",
    "iso3": "MRT",
    "Top Level Domain": "mr",
    "FIPS": "MR",
    "iso_numeric": 478,
    "GeoNameID": 2378080,
    "E164": 222,
    "phone_code": 222,
    "continent": "Africa",
    "Capital": "Nouakchott",
    "Time Zone in Capital": "Africa/Abidjan",
    "Currency": "Ouguiya",
    "Language Codes": "ar-MR,fuc,snk,fr,mey,wo",
    "Area KM2": 1030700,
  },
  {
    "name": "Mauritius",
    "iso2": "MU",
    "iso3": "MUS",
    "Top Level Domain": "mu",
    "FIPS": "MP",
    "iso_numeric": 480,
    "GeoNameID": 934292,
    "E164": 230,
    "phone_code": 230,
    "continent": "Africa",
    "Capital": "Port Louis",
    "Time Zone in Capital": "Indian/Mauritius",
    "Currency": "Rupee",
    "Language Codes": "en-MU,bho,fr",
    "Area KM2": 2040,
  },
  {
    "name": "Mayotte",
    "iso2": "YT",
    "iso3": "MYT",
    "Top Level Domain": "yt",
    "FIPS": "MF",
    "iso_numeric": 175,
    "GeoNameID": 1024031,
    "E164": 262,
    "phone_code": 262,
    "continent": "Africa",
    "Capital": "Mamoudzou",
    "Time Zone in Capital": "Indian/Mayotte",
    "Currency": "Euro",
    "Language Codes": "fr-YT",
    "Area KM2": 374,
  },
  {
    "name": "Mexico",
    "iso2": "MX",
    "iso3": "MEX",
    "Top Level Domain": "mx",
    "FIPS": "MX",
    "iso_numeric": 484,
    "GeoNameID": 3996063,
    "E164": 52,
    "phone_code": 52,
    "continent": "North America",
    "Capital": "Mexico City",
    "Time Zone in Capital": "America/Mexico_City",
    "Currency": "Peso",
    "Language Codes": "es-MX",
    "Area KM2": 1972550,
  },
  {
    "name": "Micronesia",
    "iso2": "FM",
    "iso3": "FSM",
    "Top Level Domain": "fm",
    "FIPS": "FM",
    "iso_numeric": 583,
    "GeoNameID": 2081918,
    "E164": 691,
    "phone_code": 691,
    "continent": "Oceania",
    "Capital": "Palikir",
    "Time Zone in Capital": "Pacific/Pohnpei",
    "Currency": "Dollar",
    "Language Codes": "en-FM,chk,pon,yap,kos,uli,woe,nkr,kpg",
    "Area KM2": 702,
  },
  {
    "name": "Moldova",
    "iso2": "MD",
    "iso3": "MDA",
    "Top Level Domain": "md",
    "FIPS": "MD",
    "iso_numeric": 498,
    "GeoNameID": 617790,
    "E164": 373,
    "phone_code": 373,
    "continent": "Europe",
    "Capital": "Chisinau",
    "Time Zone in Capital": "Europe/Chisinau",
    "Currency": "Leu",
    "Language Codes": "ro,ru,gag,tr",
    "Area KM2": 33843,
  },
  {
    "name": "Monaco",
    "iso2": "MC",
    "iso3": "MCO",
    "Top Level Domain": "mc",
    "FIPS": "MN",
    "iso_numeric": 492,
    "GeoNameID": 2993457,
    "E164": 377,
    "phone_code": 377,
    "continent": "Europe",
    "Capital": "Monaco",
    "Time Zone in Capital": "Europe/Monaco",
    "Currency": "Euro",
    "Language Codes": "fr-MC,en,it",
    "Area KM2": 2,
  },
  {
    "name": "Mongolia",
    "iso2": "MN",
    "iso3": "MNG",
    "Top Level Domain": "mn",
    "FIPS": "MG",
    "iso_numeric": 496,
    "GeoNameID": 2029969,
    "E164": 976,
    "phone_code": 976,
    "continent": "Asia",
    "Capital": "Ulan Bator",
    "Time Zone in Capital": "Asia/Ulaanbaatar",
    "Currency": "Tugrik",
    "Language Codes": "mn,ru",
    "Area KM2": 1565000,
  },
  {
    "name": "Montenegro",
    "iso2": "ME",
    "iso3": "MNE",
    "Top Level Domain": "me",
    "FIPS": "MJ",
    "iso_numeric": 499,
    "GeoNameID": 3194884,
    "E164": 382,
    "phone_code": 382,
    "continent": "Europe",
    "Capital": "Podgorica",
    "Time Zone in Capital": "Europe/Belgrade",
    "Currency": "Euro",
    "Language Codes": "sr,hu,bs,sq,hr,rom",
    "Area KM2": 14026,
  },
  {
    "name": "Montserrat",
    "iso2": "MS",
    "iso3": "MSR",
    "Top Level Domain": "ms",
    "FIPS": "MH",
    "iso_numeric": 500,
    "GeoNameID": 3578097,
    "E164": 1,
    "phone_code": "1-664",
    "continent": "North America",
    "Capital": "Plymouth",
    "Time Zone in Capital": "America/Port_of_Spain",
    "Currency": "Dollar",
    "Language Codes": "en-MS",
    "Area KM2": 102,
  },
  {
    "name": "Morocco",
    "iso2": "MA",
    "iso3": "MAR",
    "Top Level Domain": "ma",
    "FIPS": "MO",
    "iso_numeric": 504,
    "GeoNameID": 2542007,
    "E164": 212,
    "phone_code": 212,
    "continent": "Africa",
    "Capital": "Rabat",
    "Time Zone in Capital": "Africa/Casablanca",
    "Currency": "Dirham",
    "Language Codes": "ar-MA,fr",
    "Area KM2": 446550,
  },
  {
    "name": "Mozambique",
    "iso2": "MZ",
    "iso3": "MOZ",
    "Top Level Domain": "mz",
    "FIPS": "MZ",
    "iso_numeric": 508,
    "GeoNameID": 1036973,
    "E164": 258,
    "phone_code": 258,
    "continent": "Africa",
    "Capital": "Maputo",
    "Time Zone in Capital": "Africa/Maputo",
    "Currency": "Metical",
    "Language Codes": "pt-MZ,vmw",
    "Area KM2": 801590,
  },
  {
    "name": "Myanmar",
    "iso2": "MM",
    "iso3": "MMR",
    "Top Level Domain": "mm",
    "FIPS": "BM",
    "iso_numeric": 104,
    "GeoNameID": 1327865,
    "E164": 95,
    "phone_code": 95,
    "continent": "Asia",
    "Capital": "Nay Pyi Taw",
    "Time Zone in Capital": "Asia/Rangoon",
    "Currency": "Kyat",
    "Language Codes": "my",
    "Area KM2": 678500,
  },
  {
    "name": "Namibia",
    "iso2": "NA",
    "iso3": "NAM",
    "Top Level Domain": "na",
    "FIPS": "WA",
    "iso_numeric": 516,
    "GeoNameID": 3355338,
    "E164": 264,
    "phone_code": 264,
    "continent": "Africa",
    "Capital": "Windhoek",
    "Time Zone in Capital": "Africa/Windhoek",
    "Currency": "Dollar",
    "Language Codes": "en-NA,af,de,hz,naq",
    "Area KM2": 825418,
  },
  {
    "name": "Nauru",
    "iso2": "NR",
    "iso3": "NRU",
    "Top Level Domain": "nr",
    "FIPS": "NR",
    "iso_numeric": 520,
    "GeoNameID": 2110425,
    "E164": 674,
    "phone_code": 674,
    "continent": "Oceania",
    "Capital": "Yaren",
    "Time Zone in Capital": "Pacific/Nauru",
    "Currency": "Dollar",
    "Language Codes": "na,en-NR",
    "Area KM2": 21,
  },
  {
    "name": "Nepal",
    "iso2": "NP",
    "iso3": "NPL",
    "Top Level Domain": "np",
    "FIPS": "NP",
    "iso_numeric": 524,
    "GeoNameID": 1282988,
    "E164": 977,
    "phone_code": 977,
    "continent": "Asia",
    "Capital": "Kathmandu",
    "Time Zone in Capital": "Asia/Kathmandu",
    "Currency": "Rupee",
    "Language Codes": "ne,en",
    "Area KM2": 140800,
  },
  {
    "name": "Netherlands",
    "iso2": "NL",
    "iso3": "NLD",
    "Top Level Domain": "nl",
    "FIPS": "NL",
    "iso_numeric": 528,
    "GeoNameID": 2750405,
    "E164": 31,
    "phone_code": 31,
    "continent": "Europe",
    "Capital": "Amsterdam",
    "Time Zone in Capital": "Europe/Amsterdam",
    "Currency": "Euro",
    "Language Codes": "nl-NL,fy-NL",
    "Area KM2": 41526,
  },
  {
    "name": "Netherlands Antilles",
    "iso2": "AN",
    "iso3": "ANT",
    "Top Level Domain": "an",
    "FIPS": "NT",
    "iso_numeric": 530,
    "GeoNameID": "",
    "E164": 599,
    "phone_code": 599,
    "continent": "North America",
    "Capital": "Willemstad",
    "Time Zone in Capital": "America/Curacao",
    "Currency": "Guilder",
    "Language Codes": "nl-AN,en,es",
    "Area KM2": 960,
  },
  {
    "name": "New Caledonia",
    "iso2": "NC",
    "iso3": "NCL",
    "Top Level Domain": "nc",
    "FIPS": "NC",
    "iso_numeric": 540,
    "GeoNameID": 2139685,
    "E164": 687,
    "phone_code": 687,
    "continent": "Oceania",
    "Capital": "Noumea",
    "Time Zone in Capital": "Pacific/Noumea",
    "Currency": "Franc",
    "Language Codes": "fr-NC",
    "Area KM2": 19060,
  },
  {
    "name": "New Zealand",
    "iso2": "NZ",
    "iso3": "NZL",
    "Top Level Domain": "nz",
    "FIPS": "NZ",
    "iso_numeric": 554,
    "GeoNameID": 2186224,
    "E164": 64,
    "phone_code": 64,
    "continent": "Oceania",
    "Capital": "Wellington",
    "Time Zone in Capital": "Pacific/Auckland",
    "Currency": "Dollar",
    "Language Codes": "en-NZ,mi",
    "Area KM2": 268680,
  },
  {
    "name": "Nicaragua",
    "iso2": "NI",
    "iso3": "NIC",
    "Top Level Domain": "ni",
    "FIPS": "NU",
    "iso_numeric": 558,
    "GeoNameID": 3617476,
    "E164": 505,
    "phone_code": 505,
    "continent": "North America",
    "Capital": "Managua",
    "Time Zone in Capital": "America/Managua",
    "Currency": "Cordoba",
    "Language Codes": "es-NI,en",
    "Area KM2": 129494,
  },
  {
    "name": "Niger",
    "iso2": "NE",
    "iso3": "NER",
    "Top Level Domain": "ne",
    "FIPS": "NG",
    "iso_numeric": 562,
    "GeoNameID": 2440476,
    "E164": 227,
    "phone_code": 227,
    "continent": "Africa",
    "Capital": "Niamey",
    "Time Zone in Capital": "Africa/Lagos",
    "Currency": "Franc",
    "Language Codes": "fr-NE,ha,kr,dje",
    "Area KM2": 1267000,
  },
  {
    "name": "Nigeria",
    "iso2": "NG",
    "iso3": "NGA",
    "Top Level Domain": "ng",
    "FIPS": "NI",
    "iso_numeric": 566,
    "GeoNameID": 2328926,
    "E164": 234,
    "phone_code": 234,
    "continent": "Africa",
    "Capital": "Abuja",
    "Time Zone in Capital": "Africa/Lagos",
    "Currency": "Naira",
    "Language Codes": "en-NG,ha,yo,ig,ff",
    "Area KM2": 923768,
  },
  {
    "name": "Niue",
    "iso2": "NU",
    "iso3": "NIU",
    "Top Level Domain": "nu",
    "FIPS": "NE",
    "iso_numeric": 570,
    "GeoNameID": 4036232,
    "E164": 683,
    "phone_code": 683,
    "continent": "Oceania",
    "Capital": "Alofi",
    "Time Zone in Capital": "Pacific/Niue",
    "Currency": "Dollar",
    "Language Codes": "niu,en-NU",
    "Area KM2": 260,
  },
  {
    "name": "North Korea",
    "iso2": "KP",
    "iso3": "PRK",
    "Top Level Domain": "kp",
    "FIPS": "KN",
    "iso_numeric": 408,
    "GeoNameID": 1873107,
    "E164": 850,
    "phone_code": 850,
    "continent": "Asia",
    "Capital": "Pyongyang",
    "Time Zone in Capital": "Asia/Pyongyang",
    "Currency": "Won",
    "Language Codes": "ko-KP",
    "Area KM2": 120540,
  },
  {
    "name": "Northern Mariana Islands",
    "iso2": "MP",
    "iso3": "MNP",
    "Top Level Domain": "mp",
    "FIPS": "CQ",
    "iso_numeric": 580,
    "GeoNameID": 4041468,
    "E164": 1,
    "phone_code": "1-670",
    "continent": "Oceania",
    "Capital": "Saipan",
    "Time Zone in Capital": "Pacific/Saipan",
    "Currency": "Dollar",
    "Language Codes": "fil,tl,zh,ch-MP,en-MP",
    "Area KM2": 477,
  },
  {
    "name": "Norway",
    "iso2": "NO",
    "iso3": "NOR",
    "Top Level Domain": "no",
    "FIPS": "NO",
    "iso_numeric": 578,
    "GeoNameID": 3144096,
    "E164": 47,
    "phone_code": 47,
    "continent": "Europe",
    "Capital": "Oslo",
    "Time Zone in Capital": "Europe/Oslo",
    "Currency": "Krone",
    "Language Codes": "no,nb,nn,se,fi",
    "Area KM2": 324220,
  },
  {
    "name": "Oman",
    "iso2": "OM",
    "iso3": "OMN",
    "Top Level Domain": "om",
    "FIPS": "MU",
    "iso_numeric": 512,
    "GeoNameID": 286963,
    "E164": 968,
    "phone_code": 968,
    "continent": "Asia",
    "Capital": "Muscat",
    "Time Zone in Capital": "Asia/Muscat",
    "Currency": "Rial",
    "Language Codes": "ar-OM,en,bal,ur",
    "Area KM2": 212460,
  },
  {
    "name": "Pakistan",
    "iso2": "PK",
    "iso3": "PAK",
    "Top Level Domain": "pk",
    "FIPS": "PK",
    "iso_numeric": 586,
    "GeoNameID": 1168579,
    "E164": 92,
    "phone_code": 92,
    "continent": "Asia",
    "Capital": "Islamabad",
    "Time Zone in Capital": "Asia/Karachi",
    "Currency": "Rupee",
    "Language Codes": "ur-PK,en-PK,pa,sd,ps,brh",
    "Area KM2": 803940,
  },
  {
    "name": "Palau",
    "iso2": "PW",
    "iso3": "PLW",
    "Top Level Domain": "pw",
    "FIPS": "PS",
    "iso_numeric": 585,
    "GeoNameID": 1559582,
    "E164": 680,
    "phone_code": 680,
    "continent": "Oceania",
    "Capital": "Melekeok",
    "Time Zone in Capital": "Pacific/Palau",
    "Currency": "Dollar",
    "Language Codes": "pau,sov,en-PW,tox,ja,fil,zh",
    "Area KM2": 458,
  },
  {
    "name": "Palestine",
    "iso2": "PS",
    "iso3": "PSE",
    "Top Level Domain": "ps",
    "FIPS": "WE",
    "iso_numeric": 275,
    "GeoNameID": 6254930,
    "E164": 970,
    "phone_code": 970,
    "continent": "Asia",
    "Capital": "East Jerusalem",
    "Time Zone in Capital": "Asia/Hebron",
    "Currency": "Shekel",
    "Language Codes": "ar-PS",
    "Area KM2": 5970,
  },
  {
    "name": "Panama",
    "iso2": "PA",
    "iso3": "PAN",
    "Top Level Domain": "pa",
    "FIPS": "PM",
    "iso_numeric": 591,
    "GeoNameID": 3703430,
    "E164": 507,
    "phone_code": 507,
    "continent": "North America",
    "Capital": "Panama City",
    "Time Zone in Capital": "America/Panama",
    "Currency": "Balboa",
    "Language Codes": "es-PA,en",
    "Area KM2": 78200,
  },
  {
    "name": "Papua New Guinea",
    "iso2": "PG",
    "iso3": "PNG",
    "Top Level Domain": "pg",
    "FIPS": "PP",
    "iso_numeric": 598,
    "GeoNameID": 2088628,
    "E164": 675,
    "phone_code": 675,
    "continent": "Oceania",
    "Capital": "Port Moresby",
    "Time Zone in Capital": "Pacific/Port_Moresby",
    "Currency": "Kina",
    "Language Codes": "en-PG,ho,meu,tpi",
    "Area KM2": 462840,
  },
  {
    "name": "Paraguay",
    "iso2": "PY",
    "iso3": "PRY",
    "Top Level Domain": "py",
    "FIPS": "PA",
    "iso_numeric": 600,
    "GeoNameID": 3437598,
    "E164": 595,
    "phone_code": 595,
    "continent": "South America",
    "Capital": "Asuncion",
    "Time Zone in Capital": "America/Asuncion",
    "Currency": "Guarani",
    "Language Codes": "es-PY,gn",
    "Area KM2": 406750,
  },
  {
    "name": "Peru",
    "iso2": "PE",
    "iso3": "PER",
    "Top Level Domain": "pe",
    "FIPS": "PE",
    "iso_numeric": 604,
    "GeoNameID": 3932488,
    "E164": 51,
    "phone_code": 51,
    "continent": "South America",
    "Capital": "Lima",
    "Time Zone in Capital": "America/Lima",
    "Currency": "Sol",
    "Language Codes": "es-PE,qu,ay",
    "Area KM2": 1285220,
  },
  {
    "name": "Philippines",
    "iso2": "PH",
    "iso3": "PHL",
    "Top Level Domain": "ph",
    "FIPS": "RP",
    "iso_numeric": 608,
    "GeoNameID": 1694008,
    "E164": 63,
    "phone_code": 63,
    "continent": "Asia",
    "Capital": "Manila",
    "Time Zone in Capital": "Asia/Manila",
    "Currency": "Peso",
    "Language Codes": "tl,en-PH,fil",
    "Area KM2": 300000,
  },
  {
    "name": "Pitcairn",
    "iso2": "PN",
    "iso3": "PCN",
    "Top Level Domain": "pn",
    "FIPS": "PC",
    "iso_numeric": 612,
    "GeoNameID": 4030699,
    "E164": 64,
    "phone_code": 64,
    "continent": "Oceania",
    "Capital": "Adamstown",
    "Time Zone in Capital": "Pacific/Pitcairn",
    "Currency": "Dollar",
    "Language Codes": "en-PN",
    "Area KM2": 47,
  },
  {
    "name": "Poland",
    "iso2": "PL",
    "iso3": "POL",
    "Top Level Domain": "pl",
    "FIPS": "PL",
    "iso_numeric": 616,
    "GeoNameID": 798544,
    "E164": 48,
    "phone_code": 48,
    "continent": "Europe",
    "Capital": "Warsaw",
    "Time Zone in Capital": "Europe/Warsaw",
    "Currency": "Zloty",
    "Language Codes": "pl",
    "Area KM2": 312685,
  },
  {
    "name": "Portugal",
    "iso2": "PT",
    "iso3": "PRT",
    "Top Level Domain": "pt",
    "FIPS": "PO",
    "iso_numeric": 620,
    "GeoNameID": 2264397,
    "E164": 351,
    "phone_code": 351,
    "continent": "Europe",
    "Capital": "Lisbon",
    "Time Zone in Capital": "Europe/Lisbon",
    "Currency": "Euro",
    "Language Codes": "pt-PT,mwl",
    "Area KM2": 92391,
  },
  {
    "name": "Puerto Rico",
    "iso2": "PR",
    "iso3": "PRI",
    "Top Level Domain": "pr",
    "FIPS": "RQ",
    "iso_numeric": 630,
    "GeoNameID": 4566966,
    "E164": 1,
    "phone_code": "1-787, 1-939",
    "continent": "North America",
    "Capital": "San Juan",
    "Time Zone in Capital": "America/Puerto_Rico",
    "Currency": "Dollar",
    "Language Codes": "en-PR,es-PR",
    "Area KM2": 9104,
  },
  {
    "name": "Qatar",
    "iso2": "QA",
    "iso3": "QAT",
    "Top Level Domain": "qa",
    "FIPS": "QA",
    "iso_numeric": 634,
    "GeoNameID": 289688,
    "E164": 974,
    "phone_code": 974,
    "continent": "Asia",
    "Capital": "Doha",
    "Time Zone in Capital": "Asia/Qatar",
    "Currency": "Rial",
    "Language Codes": "ar-QA,es",
    "Area KM2": 11437,
  },
  {
    "name": "Republic of the Congo",
    "iso2": "CG",
    "iso3": "COG",
    "Top Level Domain": "cg",
    "FIPS": "CF",
    "iso_numeric": 178,
    "GeoNameID": 2260494,
    "E164": 242,
    "phone_code": 242,
    "continent": "Africa",
    "Capital": "Brazzaville",
    "Time Zone in Capital": "Africa/Lagos",
    "Currency": "Franc",
    "Language Codes": "fr-CG,kg,ln-CG",
    "Area KM2": 342000,
  },
  {
    "name": "Reunion",
    "iso2": "RE",
    "iso3": "REU",
    "Top Level Domain": "re",
    "FIPS": "RE",
    "iso_numeric": 638,
    "GeoNameID": 935317,
    "E164": 262,
    "phone_code": 262,
    "continent": "Africa",
    "Capital": "Saint-Denis",
    "Time Zone in Capital": "Indian/Reunion",
    "Currency": "Euro",
    "Language Codes": "fr-RE",
    "Area KM2": 2517,
  },
  {
    "name": "Romania",
    "iso2": "RO",
    "iso3": "ROU",
    "Top Level Domain": "ro",
    "FIPS": "RO",
    "iso_numeric": 642,
    "GeoNameID": 798549,
    "E164": 40,
    "phone_code": 40,
    "continent": "Europe",
    "Capital": "Bucharest",
    "Time Zone in Capital": "Europe/Bucharest",
    "Currency": "Leu",
    "Language Codes": "ro,hu,rom",
    "Area KM2": 237500,
  },
  {
    "name": "Russia",
    "iso2": "RU",
    "iso3": "RUS",
    "Top Level Domain": "ru",
    "FIPS": "RS",
    "iso_numeric": 643,
    "GeoNameID": 2017370,
    "E164": 7,
    "phone_code": 7,
    "continent": "Europe",
    "Capital": "Moscow",
    "Time Zone in Capital": "Europe/Moscow",
    "Currency": "Ruble",
    "Language Codes": "ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,ava,sah,nog",
    "Area KM2": 17100000,
  },
  {
    "name": "Rwanda",
    "iso2": "RW",
    "iso3": "RWA",
    "Top Level Domain": "rw",
    "FIPS": "RW",
    "iso_numeric": 646,
    "GeoNameID": 49518,
    "E164": 250,
    "phone_code": 250,
    "continent": "Africa",
    "Capital": "Kigali",
    "Time Zone in Capital": "Africa/Maputo",
    "Currency": "Franc",
    "Language Codes": "rw,en-RW,fr-RW,sw",
    "Area KM2": 26338,
  },
  {
    "name": "Saint Barthelemy",
    "iso2": "BL",
    "iso3": "BLM",
    "Top Level Domain": "gp",
    "FIPS": "TB",
    "iso_numeric": 652,
    "GeoNameID": 3578476,
    "E164": 590,
    "phone_code": 590,
    "continent": "North America",
    "Capital": "Gustavia",
    "Time Zone in Capital": "America/Port_of_Spain",
    "Currency": "Euro",
    "Language Codes": "fr",
    "Area KM2": 21,
  },
  {
    "name": "Saint Helena",
    "iso2": "SH",
    "iso3": "SHN",
    "Top Level Domain": "sh",
    "FIPS": "SH",
    "iso_numeric": 654,
    "GeoNameID": 3370751,
    "E164": 290,
    "phone_code": 290,
    "continent": "Africa",
    "Capital": "Jamestown",
    "Time Zone in Capital": "Africa/Abidjan",
    "Currency": "Pound",
    "Language Codes": "en-SH",
    "Area KM2": 410,
  },
  {
    "name": "Saint Kitts and Nevis",
    "iso2": "KN",
    "iso3": "KNA",
    "Top Level Domain": "kn",
    "FIPS": "SC",
    "iso_numeric": 659,
    "GeoNameID": 3575174,
    "E164": 1,
    "phone_code": "1-869",
    "continent": "North America",
    "Capital": "Basseterre",
    "Time Zone in Capital": "America/Port_of_Spain",
    "Currency": "Dollar",
    "Language Codes": "en-KN",
    "Area KM2": 261,
  },
  {
    "name": "Saint Lucia",
    "iso2": "LC",
    "iso3": "LCA",
    "Top Level Domain": "lc",
    "FIPS": "ST",
    "iso_numeric": 662,
    "GeoNameID": 3576468,
    "E164": 1,
    "phone_code": "1-758",
    "continent": "North America",
    "Capital": "Castries",
    "Time Zone in Capital": "America/Port_of_Spain",
    "Currency": "Dollar",
    "Language Codes": "en-LC",
    "Area KM2": 616,
  },
  {
    "name": "Saint Martin",
    "iso2": "MF",
    "iso3": "MAF",
    "Top Level Domain": "gp",
    "FIPS": "RN",
    "iso_numeric": 663,
    "GeoNameID": 3578421,
    "E164": 1,
    "phone_code": 590,
    "continent": "North America",
    "Capital": "Marigot",
    "Time Zone in Capital": "America/Port_of_Spain",
    "Currency": "Euro",
    "Language Codes": "fr",
    "Area KM2": 53,
  },
  {
    "name": "Saint Pierre and Miquelon",
    "iso2": "PM",
    "iso3": "SPM",
    "Top Level Domain": "pm",
    "FIPS": "SB",
    "iso_numeric": 666,
    "GeoNameID": 3424932,
    "E164": 508,
    "phone_code": 508,
    "continent": "North America",
    "Capital": "Saint-Pierre",
    "Time Zone in Capital": "America/Miquelon",
    "Currency": "Euro",
    "Language Codes": "fr-PM",
    "Area KM2": 242,
  },
  {
    "name": "Saint Vincent and the Grenadines",
    "iso2": "VC",
    "iso3": "VCT",
    "Top Level Domain": "vc",
    "FIPS": "VC",
    "iso_numeric": 670,
    "GeoNameID": 3577815,
    "E164": 1,
    "phone_code": "1-784",
    "continent": "North America",
    "Capital": "Kingstown",
    "Time Zone in Capital": "America/Port_of_Spain",
    "Currency": "Dollar",
    "Language Codes": "en-VC,fr",
    "Area KM2": 389,
  },
  {
    "name": "Samoa",
    "iso2": "WS",
    "iso3": "WSM",
    "Top Level Domain": "ws",
    "FIPS": "WS",
    "iso_numeric": 882,
    "GeoNameID": 4034894,
    "E164": 685,
    "phone_code": 685,
    "continent": "Oceania",
    "Capital": "Apia",
    "Time Zone in Capital": "Pacific/Apia",
    "Currency": "Tala",
    "Language Codes": "sm,en-WS",
    "Area KM2": 2944,
  },
  {
    "name": "San Marino",
    "iso2": "SM",
    "iso3": "SMR",
    "Top Level Domain": "sm",
    "FIPS": "SM",
    "iso_numeric": 674,
    "GeoNameID": 3168068,
    "E164": 378,
    "phone_code": 378,
    "continent": "Europe",
    "Capital": "San Marino",
    "Time Zone in Capital": "Europe/Rome",
    "Currency": "Euro",
    "Language Codes": "it-SM",
    "Area KM2": 61,
  },
  {
    "name": "Sao Tome and Principe",
    "iso2": "ST",
    "iso3": "STP",
    "Top Level Domain": "st",
    "FIPS": "TP",
    "iso_numeric": 678,
    "GeoNameID": 2410758,
    "E164": 239,
    "phone_code": 239,
    "continent": "Africa",
    "Capital": "Sao Tome",
    "Time Zone in Capital": "Africa/Abidjan",
    "Currency": "Dobra",
    "Language Codes": "pt-ST",
    "Area KM2": 1001,
  },
  {
    "name": "Saudi Arabia",
    "iso2": "SA",
    "iso3": "SAU",
    "Top Level Domain": "sa",
    "FIPS": "SA",
    "iso_numeric": 682,
    "GeoNameID": 102358,
    "E164": 966,
    "phone_code": 966,
    "continent": "Asia",
    "Capital": "Riyadh",
    "Time Zone in Capital": "Asia/Riyadh",
    "Currency": "Rial",
    "Language Codes": "ar-SA",
    "Area KM2": 1960582,
  },
  {
    "name": "Senegal",
    "iso2": "SN",
    "iso3": "SEN",
    "Top Level Domain": "sn",
    "FIPS": "SG",
    "iso_numeric": 686,
    "GeoNameID": 2245662,
    "E164": 221,
    "phone_code": 221,
    "continent": "Africa",
    "Capital": "Dakar",
    "Time Zone in Capital": "Africa/Abidjan",
    "Currency": "Franc",
    "Language Codes": "fr-SN,wo,fuc,mnk",
    "Area KM2": 196190,
  },
  {
    "name": "Serbia",
    "iso2": "RS",
    "iso3": "SRB",
    "Top Level Domain": "rs",
    "FIPS": "RI",
    "iso_numeric": 688,
    "GeoNameID": 6290252,
    "E164": 381,
    "phone_code": 381,
    "continent": "Europe",
    "Capital": "Belgrade",
    "Time Zone in Capital": "Europe/Belgrade",
    "Currency": "Dinar",
    "Language Codes": "sr,hu,bs,rom",
    "Area KM2": 88361,
  },
  {
    "name": "Seychelles",
    "iso2": "SC",
    "iso3": "SYC",
    "Top Level Domain": "sc",
    "FIPS": "SE",
    "iso_numeric": 690,
    "GeoNameID": 241170,
    "E164": 248,
    "phone_code": 248,
    "continent": "Africa",
    "Capital": "Victoria",
    "Time Zone in Capital": "Indian/Mahe",
    "Currency": "Rupee",
    "Language Codes": "en-SC,fr-SC",
    "Area KM2": 455,
  },
  {
    "name": "Sierra Leone",
    "iso2": "SL",
    "iso3": "SLE",
    "Top Level Domain": "sl",
    "FIPS": "SL",
    "iso_numeric": 694,
    "GeoNameID": 2403846,
    "E164": 232,
    "phone_code": 232,
    "continent": "Africa",
    "Capital": "Freetown",
    "Time Zone in Capital": "Africa/Abidjan",
    "Currency": "Leone",
    "Language Codes": "en-SL,men,tem",
    "Area KM2": 71740,
  },
  {
    "name": "Singapore",
    "iso2": "SG",
    "iso3": "SGP",
    "Top Level Domain": "sg",
    "FIPS": "SN",
    "iso_numeric": 702,
    "GeoNameID": 1880251,
    "E164": 65,
    "phone_code": 65,
    "continent": "Asia",
    "Capital": "Singapore",
    "Time Zone in Capital": "Asia/Singapore",
    "Currency": "Dollar",
    "Language Codes": "cmn,en-SG,ms-SG,ta-SG,zh-SG",
    "Area KM2": 693,
  },
  {
    "name": "Sint Maarten",
    "iso2": "SX",
    "iso3": "SXM",
    "Top Level Domain": "sx",
    "FIPS": "NN",
    "iso_numeric": 534,
    "GeoNameID": 7609695,
    "E164": 1,
    "phone_code": "1-721",
    "continent": "North America",
    "Capital": "Philipsburg",
    "Time Zone in Capital": "America/Curacao",
    "Currency": "Guilder",
    "Language Codes": "nl,en",
    "Area KM2": 34,
  },
  {
    "name": "Slovakia",
    "iso2": "SK",
    "iso3": "SVK",
    "Top Level Domain": "sk",
    "FIPS": "LO",
    "iso_numeric": 703,
    "GeoNameID": 3057568,
    "E164": 421,
    "phone_code": 421,
    "continent": "Europe",
    "Capital": "Bratislava",
    "Time Zone in Capital": "Europe/Prague",
    "Currency": "Euro",
    "Language Codes": "sk,hu",
    "Area KM2": 48845,
  },
  {
    "name": "Slovenia",
    "iso2": "SI",
    "iso3": "SVN",
    "Top Level Domain": "si",
    "FIPS": "SI",
    "iso_numeric": 705,
    "GeoNameID": 3190538,
    "E164": 386,
    "phone_code": 386,
    "continent": "Europe",
    "Capital": "Ljubljana",
    "Time Zone in Capital": "Europe/Belgrade",
    "Currency": "Euro",
    "Language Codes": "sl,sh",
    "Area KM2": 20273,
  },
  {
    "name": "Solomon Islands",
    "iso2": "SB",
    "iso3": "SLB",
    "Top Level Domain": "sb",
    "FIPS": "BP",
    "iso_numeric": "090",
    "GeoNameID": 2103350,
    "E164": 677,
    "phone_code": 677,
    "continent": "Oceania",
    "Capital": "Honiara",
    "Time Zone in Capital": "Pacific/Guadalcanal",
    "Currency": "Dollar",
    "Language Codes": "en-SB,tpi",
    "Area KM2": 28450,
  },
  {
    "name": "Somalia",
    "iso2": "SO",
    "iso3": "SOM",
    "Top Level Domain": "so",
    "FIPS": "SO",
    "iso_numeric": 706,
    "GeoNameID": 51537,
    "E164": 252,
    "phone_code": 252,
    "continent": "Africa",
    "Capital": "Mogadishu",
    "Time Zone in Capital": "Africa/Mogadishu",
    "Currency": "Shilling",
    "Language Codes": "so-SO,ar-SO,it,en-SO",
    "Area KM2": 637657,
  },
  {
    "name": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "Top Level Domain": "za",
    "FIPS": "SF",
    "iso_numeric": 710,
    "GeoNameID": 953987,
    "E164": 27,
    "phone_code": 27,
    "continent": "Africa",
    "Capital": "Pretoria",
    "Time Zone in Capital": "Africa/Johannesburg",
    "Currency": "Rand",
    "Language Codes": "zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr",
    "Area KM2": 1219912,
  },
  {
    "name": "South Korea",
    "iso2": "KR",
    "iso3": "KOR",
    "Top Level Domain": "kr",
    "FIPS": "KS",
    "iso_numeric": 410,
    "GeoNameID": 1835841,
    "E164": 82,
    "phone_code": 82,
    "continent": "Asia",
    "Capital": "Seoul",
    "Time Zone in Capital": "Asia/Seoul",
    "Currency": "Won",
    "Language Codes": "ko-KR,en",
    "Area KM2": 98480,
  },
  {
    "name": "South Sudan",
    "iso2": "SS",
    "iso3": "SSD",
    "Top Level Domain": "ss",
    "FIPS": "OD",
    "iso_numeric": 728,
    "GeoNameID": 7909807,
    "E164": 211,
    "phone_code": 211,
    "continent": "Africa",
    "Capital": "Juba",
    "Time Zone in Capital": "Africa/Khartoum",
    "Currency": "Pound",
    "Language Codes": "en",
    "Area KM2": 644329,
  },
  {
    "name": "Spain",
    "iso2": "ES",
    "iso3": "ESP",
    "Top Level Domain": "es",
    "FIPS": "SP",
    "iso_numeric": 724,
    "GeoNameID": 2510769,
    "E164": 34,
    "phone_code": 34,
    "continent": "Europe",
    "Capital": "Madrid",
    "Time Zone in Capital": "Europe/Madrid",
    "Currency": "Euro",
    "Language Codes": "es-ES,ca,gl,eu,oc",
    "Area KM2": 504782,
  },
  {
    "name": "Sri Lanka",
    "iso2": "LK",
    "iso3": "LKA",
    "Top Level Domain": "lk",
    "FIPS": "CE",
    "iso_numeric": 144,
    "GeoNameID": 1227603,
    "E164": 94,
    "phone_code": 94,
    "continent": "Asia",
    "Capital": "Colombo",
    "Time Zone in Capital": "Asia/Colombo",
    "Currency": "Rupee",
    "Language Codes": "si,ta,en",
    "Area KM2": 65610,
  },
  {
    "name": "Sudan",
    "iso2": "SD",
    "iso3": "SDN",
    "Top Level Domain": "sd",
    "FIPS": "SU",
    "iso_numeric": 729,
    "GeoNameID": 366755,
    "E164": 249,
    "phone_code": 249,
    "continent": "Africa",
    "Capital": "Khartoum",
    "Time Zone in Capital": "Africa/Khartoum",
    "Currency": "Pound",
    "Language Codes": "ar-SD,en,fia",
    "Area KM2": 1861484,
  },
  {
    "name": "Suriname",
    "iso2": "SR",
    "iso3": "SUR",
    "Top Level Domain": "sr",
    "FIPS": "NS",
    "iso_numeric": 740,
    "GeoNameID": 3382998,
    "E164": 597,
    "phone_code": 597,
    "continent": "South America",
    "Capital": "Paramaribo",
    "Time Zone in Capital": "America/Paramaribo",
    "Currency": "Dollar",
    "Language Codes": "nl-SR,en,srn,hns,jv",
    "Area KM2": 163270,
  },
  {
    "name": "Svalbard and Jan Mayen",
    "iso2": "SJ",
    "iso3": "SJM",
    "Top Level Domain": "sj",
    "FIPS": "SV",
    "iso_numeric": 744,
    "GeoNameID": 607072,
    "E164": 47,
    "phone_code": 47,
    "continent": "Europe",
    "Capital": "Longyearbyen",
    "Time Zone in Capital": "Europe/Oslo",
    "Currency": "Krone",
    "Language Codes": "no,ru",
    "Area KM2": 62049,
  },
  {
    "name": "Swaziland",
    "iso2": "SZ",
    "iso3": "SWZ",
    "Top Level Domain": "sz",
    "FIPS": "WZ",
    "iso_numeric": 748,
    "GeoNameID": 934841,
    "E164": 268,
    "phone_code": 268,
    "continent": "Africa",
    "Capital": "Mbabane",
    "Time Zone in Capital": "Africa/Johannesburg",
    "Currency": "Lilangeni",
    "Language Codes": "en-SZ,ss-SZ",
    "Area KM2": 17363,
  },
  {
    "name": "Sweden",
    "iso2": "SE",
    "iso3": "SWE",
    "Top Level Domain": "se",
    "FIPS": "SW",
    "iso_numeric": 752,
    "GeoNameID": 2661886,
    "E164": 46,
    "phone_code": 46,
    "continent": "Europe",
    "Capital": "Stockholm",
    "Time Zone in Capital": "Europe/Stockholm",
    "Currency": "Krona",
    "Language Codes": "sv-SE,se,sma,fi-SE",
    "Area KM2": 449964,
  },
  {
    "name": "Switzerland",
    "iso2": "CH",
    "iso3": "CHE",
    "Top Level Domain": "ch",
    "FIPS": "SZ",
    "iso_numeric": 756,
    "GeoNameID": 2658434,
    "E164": 41,
    "phone_code": 41,
    "continent": "Europe",
    "Capital": "Berne",
    "Time Zone in Capital": "Europe/Zurich",
    "Currency": "Franc",
    "Language Codes": "de-CH,fr-CH,it-CH,rm",
    "Area KM2": 41290,
  },
  {
    "name": "Syria",
    "iso2": "SY",
    "iso3": "SYR",
    "Top Level Domain": "sy",
    "FIPS": "SY",
    "iso_numeric": 760,
    "GeoNameID": 163843,
    "E164": 963,
    "phone_code": 963,
    "continent": "Asia",
    "Capital": "Damascus",
    "Time Zone in Capital": "Asia/Damascus",
    "Currency": "Pound",
    "Language Codes": "ar-SY,ku,hy,arc,fr,en",
    "Area KM2": 185180,
  },
  {
    "name": "Taiwan",
    "iso2": "TW",
    "iso3": "TWN",
    "Top Level Domain": "tw",
    "FIPS": "TW",
    "iso_numeric": 158,
    "GeoNameID": 1668284,
    "E164": 886,
    "phone_code": 886,
    "continent": "Asia",
    "Capital": "Taipei",
    "Time Zone in Capital": "Asia/Taipei",
    "Currency": "Dollar",
    "Language Codes": "zh-TW,zh,nan,hak",
    "Area KM2": 35980,
  },
  {
    "name": "Tajikistan",
    "iso2": "TJ",
    "iso3": "TJK",
    "Top Level Domain": "tj",
    "FIPS": "TI",
    "iso_numeric": 762,
    "GeoNameID": 1220409,
    "E164": 992,
    "phone_code": 992,
    "continent": "Asia",
    "Capital": "Dushanbe",
    "Time Zone in Capital": "Asia/Dushanbe",
    "Currency": "Somoni",
    "Language Codes": "tg,ru",
    "Area KM2": 143100,
  },
  {
    "name": "Tanzania",
    "iso2": "TZ",
    "iso3": "TZA",
    "Top Level Domain": "tz",
    "FIPS": "TZ",
    "iso_numeric": 834,
    "GeoNameID": 149590,
    "E164": 255,
    "phone_code": 255,
    "continent": "Africa",
    "Capital": "Dodoma",
    "Time Zone in Capital": "Africa/Dar_es_Salaam",
    "Currency": "Shilling",
    "Language Codes": "sw-TZ,en,ar",
    "Area KM2": 945087,
  },
  {
    "name": "Thailand",
    "iso2": "TH",
    "iso3": "THA",
    "Top Level Domain": "th",
    "FIPS": "TH",
    "iso_numeric": 764,
    "GeoNameID": 1605651,
    "E164": 66,
    "phone_code": 66,
    "continent": "Asia",
    "Capital": "Bangkok",
    "Time Zone in Capital": "Asia/Bangkok",
    "Currency": "Baht",
    "Language Codes": "th,en",
    "Area KM2": 514000,
  },
  {
    "name": "Togo",
    "iso2": "TG",
    "iso3": "TGO",
    "Top Level Domain": "tg",
    "FIPS": "TO",
    "iso_numeric": 768,
    "GeoNameID": 2363686,
    "E164": 228,
    "phone_code": 228,
    "continent": "Africa",
    "Capital": "Lome",
    "Time Zone in Capital": "Africa/Abidjan",
    "Currency": "Franc",
    "Language Codes": "fr-TG,ee,hna,kbp,dag,ha",
    "Area KM2": 56785,
  },
  {
    "name": "Tokelau",
    "iso2": "TK",
    "iso3": "TKL",
    "Top Level Domain": "tk",
    "FIPS": "TL",
    "iso_numeric": 772,
    "GeoNameID": 4031074,
    "E164": 690,
    "phone_code": 690,
    "continent": "Oceania",
    "Capital": "",
    "Time Zone in Capital": "Pacific/Fakaofo",
    "Currency": "Dollar",
    "Language Codes": "tkl,en-TK",
    "Area KM2": 10,
  },
  {
    "name": "Tonga",
    "iso2": "TO",
    "iso3": "TON",
    "Top Level Domain": "to",
    "FIPS": "TN",
    "iso_numeric": 776,
    "GeoNameID": 4032283,
    "E164": 676,
    "phone_code": 676,
    "continent": "Oceania",
    "Capital": "Nuku'alofa",
    "Time Zone in Capital": "Pacific/Tongatapu",
    "Currency": "Pa'anga",
    "Language Codes": "to,en-TO",
    "Area KM2": 748,
  },
  {
    "name": "Trinidad and Tobago",
    "iso2": "TT",
    "iso3": "TTO",
    "Top Level Domain": "tt",
    "FIPS": "TD",
    "iso_numeric": 780,
    "GeoNameID": 3573591,
    "E164": 1,
    "phone_code": "1-868",
    "continent": "North America",
    "Capital": "Port of Spain",
    "Time Zone in Capital": "America/Port_of_Spain",
    "Currency": "Dollar",
    "Language Codes": "en-TT,hns,fr,es,zh",
    "Area KM2": 5128,
  },
  {
    "name": "Tunisia",
    "iso2": "TN",
    "iso3": "TUN",
    "Top Level Domain": "tn",
    "FIPS": "TS",
    "iso_numeric": 788,
    "GeoNameID": 2464461,
    "E164": 216,
    "phone_code": 216,
    "continent": "Africa",
    "Capital": "Tunis",
    "Time Zone in Capital": "Africa/Tunis",
    "Currency": "Dinar",
    "Language Codes": "ar-TN,fr",
    "Area KM2": 163610,
  },
  {
    "name": "Turkey",
    "iso2": "TR",
    "iso3": "TUR",
    "Top Level Domain": "tr",
    "FIPS": "TU",
    "iso_numeric": 792,
    "GeoNameID": 298795,
    "E164": 90,
    "phone_code": 90,
    "continent": "Asia",
    "Capital": "Ankara",
    "Time Zone in Capital": "Europe/Istanbul",
    "Currency": "Lira",
    "Language Codes": "tr-TR,ku,diq,az,av",
    "Area KM2": 780580,
  },
  {
    "name": "Turkmenistan",
    "iso2": "TM",
    "iso3": "TKM",
    "Top Level Domain": "tm",
    "FIPS": "TX",
    "iso_numeric": 795,
    "GeoNameID": 1218197,
    "E164": 993,
    "phone_code": 993,
    "continent": "Asia",
    "Capital": "Ashgabat",
    "Time Zone in Capital": "Asia/Ashgabat",
    "Currency": "Manat",
    "Language Codes": "tk,ru,uz",
    "Area KM2": 488100,
  },
  {
    "name": "Turks and Caicos Islands",
    "iso2": "TC",
    "iso3": "TCA",
    "Top Level Domain": "tc",
    "FIPS": "TK",
    "iso_numeric": 796,
    "GeoNameID": 3576916,
    "E164": 1,
    "phone_code": "1-649",
    "continent": "North America",
    "Capital": "Cockburn Town",
    "Time Zone in Capital": "America/Grand_Turk",
    "Currency": "Dollar",
    "Language Codes": "en-TC",
    "Area KM2": 430,
  },
  {
    "name": "Tuvalu",
    "iso2": "TV",
    "iso3": "TUV",
    "Top Level Domain": "tv",
    "FIPS": "TV",
    "iso_numeric": 798,
    "GeoNameID": 2110297,
    "E164": 688,
    "phone_code": 688,
    "continent": "Oceania",
    "Capital": "Funafuti",
    "Time Zone in Capital": "Pacific/Funafuti",
    "Currency": "Dollar",
    "Language Codes": "tvl,en,sm,gil",
    "Area KM2": 26,
  },
  {
    "name": "U.S. Virgin Islands",
    "iso2": "VI",
    "iso3": "VIR",
    "Top Level Domain": "vi",
    "FIPS": "VQ",
    "iso_numeric": 850,
    "GeoNameID": 4796775,
    "E164": 1,
    "phone_code": "1-340",
    "continent": "North America",
    "Capital": "Charlotte Amalie",
    "Time Zone in Capital": "America/Port_of_Spain",
    "Currency": "Dollar",
    "Language Codes": "en-VI",
    "Area KM2": 352,
  },
  {
    "name": "Uganda",
    "iso2": "UG",
    "iso3": "UGA",
    "Top Level Domain": "ug",
    "FIPS": "UG",
    "iso_numeric": 800,
    "GeoNameID": 226074,
    "E164": 256,
    "phone_code": 256,
    "continent": "Africa",
    "Capital": "Kampala",
    "Time Zone in Capital": "Africa/Kampala",
    "Currency": "Shilling",
    "Language Codes": "en-UG,lg,sw,ar",
    "Area KM2": 236040,
  },
  {
    "name": "Ukraine",
    "iso2": "UA",
    "iso3": "UKR",
    "Top Level Domain": "ua",
    "FIPS": "UP",
    "iso_numeric": 804,
    "GeoNameID": 690791,
    "E164": 380,
    "phone_code": 380,
    "continent": "Europe",
    "Capital": "Kiev",
    "Time Zone in Capital": "Europe/Kiev",
    "Currency": "Hryvnia",
    "Language Codes": "uk,ru-UA,rom,pl,hu",
    "Area KM2": 603700,
  },
  {
    "name": "United Arab Emirates",
    "iso2": "AE",
    "iso3": "ARE",
    "Top Level Domain": "ae",
    "FIPS": "AE",
    "iso_numeric": 784,
    "GeoNameID": 290557,
    "E164": 971,
    "phone_code": 971,
    "continent": "Asia",
    "Capital": "Abu Dhabi",
    "Time Zone in Capital": "Asia/Dubai",
    "Currency": "Dirham",
    "Language Codes": "ar-AE,fa,en,hi,ur",
    "Area KM2": 82880,
  },
  {
    "name": "United Kingdom",
    "iso2": "GB",
    "iso3": "GBR",
    "Top Level Domain": "uk",
    "FIPS": "UK",
    "iso_numeric": 826,
    "GeoNameID": 2635167,
    "E164": 44,
    "phone_code": 44,
    "continent": "Europe",
    "Capital": "London",
    "Time Zone in Capital": "Europe/London",
    "Currency": "Pound",
    "Language Codes": "en-GB,cy-GB,gd",
    "Area KM2": 244820,
  },
  {
    "name": "Uruguay",
    "iso2": "UY",
    "iso3": "URY",
    "Top Level Domain": "uy",
    "FIPS": "UY",
    "iso_numeric": 858,
    "GeoNameID": 3439705,
    "E164": 598,
    "phone_code": 598,
    "continent": "South America",
    "Capital": "Montevideo",
    "Time Zone in Capital": "America/Montevideo",
    "Currency": "Peso",
    "Language Codes": "es-UY",
    "Area KM2": 176220,
  },
  {
    "name": "Uzbekistan",
    "iso2": "UZ",
    "iso3": "UZB",
    "Top Level Domain": "uz",
    "FIPS": "UZ",
    "iso_numeric": 860,
    "GeoNameID": 1512440,
    "E164": 998,
    "phone_code": 998,
    "continent": "Asia",
    "Capital": "Tashkent",
    "Time Zone in Capital": "Asia/Tashkent",
    "Currency": "Som",
    "Language Codes": "uz,ru,tg",
    "Area KM2": 447400,
  },
  {
    "name": "Vanuatu",
    "iso2": "VU",
    "iso3": "VUT",
    "Top Level Domain": "vu",
    "FIPS": "NH",
    "iso_numeric": 548,
    "GeoNameID": 2134431,
    "E164": 678,
    "phone_code": 678,
    "continent": "Oceania",
    "Capital": "Port Vila",
    "Time Zone in Capital": "Pacific/Efate",
    "Currency": "Vatu",
    "Language Codes": "bi,en-VU,fr-VU",
    "Area KM2": 12200,
  },
  {
    "name": "Vatican",
    "iso2": "VA",
    "iso3": "VAT",
    "Top Level Domain": "va",
    "FIPS": "VT",
    "iso_numeric": 336,
    "GeoNameID": 3164670,
    "E164": 39,
    "phone_code": 379,
    "continent": "Europe",
    "Capital": "Vatican City",
    "Time Zone in Capital": "Europe/Rome",
    "Currency": "Euro",
    "Language Codes": "la,it,fr",
    "Area KM2": 0,
  },
  {
    "name": "Venezuela",
    "iso2": "VE",
    "iso3": "VEN",
    "Top Level Domain": "ve",
    "FIPS": "VE",
    "iso_numeric": 862,
    "GeoNameID": 3625428,
    "E164": 58,
    "phone_code": 58,
    "continent": "South America",
    "Capital": "Caracas",
    "Time Zone in Capital": "America/Caracas",
    "Currency": "Bolivar",
    "Language Codes": "es-VE",
    "Area KM2": 912050,
  },
  {
    "name": "Vietnam",
    "iso2": "VN",
    "iso3": "VNM",
    "Top Level Domain": "vn",
    "FIPS": "VM",
    "iso_numeric": 704,
    "GeoNameID": 1562822,
    "E164": 84,
    "phone_code": 84,
    "continent": "Asia",
    "Capital": "Hanoi",
    "Time Zone in Capital": "Asia/Ho_Chi_Minh",
    "Currency": "Dong",
    "Language Codes": "vi,en,fr,zh,km",
    "Area KM2": 329560,
  },
  {
    "name": "Wallis and Futuna",
    "iso2": "WF",
    "iso3": "WLF",
    "Top Level Domain": "wf",
    "FIPS": "WF",
    "iso_numeric": 876,
    "GeoNameID": 4034749,
    "E164": 681,
    "phone_code": 681,
    "continent": "Oceania",
    "Capital": "Mata Utu",
    "Time Zone in Capital": "Pacific/Wallis",
    "Currency": "Franc",
    "Language Codes": "wls,fud,fr-WF",
    "Area KM2": 274,
  },
  {
    "name": "Western Sahara",
    "iso2": "EH",
    "iso3": "ESH",
    "Top Level Domain": "eh",
    "FIPS": "WI",
    "iso_numeric": 732,
    "GeoNameID": 2461445,
    "E164": 212,
    "phone_code": 212,
    "continent": "Africa",
    "Capital": "El-Aaiun",
    "Time Zone in Capital": "Africa/El_Aaiun",
    "Currency": "Dirham",
    "Language Codes": "ar,mey",
    "Area KM2": 266000,
  },
  {
    "name": "Yemen",
    "iso2": "YE",
    "iso3": "YEM",
    "Top Level Domain": "ye",
    "FIPS": "YM",
    "iso_numeric": 887,
    "GeoNameID": 69543,
    "E164": 967,
    "phone_code": 967,
    "continent": "Asia",
    "Capital": "Sanaa",
    "Time Zone in Capital": "Asia/Aden",
    "Currency": "Rial",
    "Language Codes": "ar-YE",
    "Area KM2": 527970,
  },
  {
    "name": "Zambia",
    "iso2": "ZM",
    "iso3": "ZMB",
    "Top Level Domain": "zm",
    "FIPS": "ZA",
    "iso_numeric": 894,
    "GeoNameID": 895949,
    "E164": 260,
    "phone_code": 260,
    "continent": "Africa",
    "Capital": "Lusaka",
    "Time Zone in Capital": "Africa/Maputo",
    "Currency": "Kwacha",
    "Language Codes": "en-ZM,bem,loz,lun,lue,ny,toi",
    "Area KM2": 752614,
  },
  {
    "name": "Zimbabwe",
    "iso2": "ZW",
    "iso3": "ZWE",
    "Top Level Domain": "zw",
    "FIPS": "ZI",
    "iso_numeric": 716,
    "GeoNameID": 878675,
    "E164": 263,
    "phone_code": 263,
    "continent": "Africa",
    "Capital": "Harare",
    "Time Zone in Capital": "Africa/Maputo",
    "Currency": "Dollar",
    "Language Codes": "en-ZW,sn,nr,nd",
    "Area KM2": 390580,
  }
]

class CountryAlpha2Model(BaseModel):
    id: str
    country_name: str
    continent: str

@router.get('/iso2')
def list_countries_in_iso2(
        response: Response,
        _sort: Optional[str] = Query("country_name", description="sort by country_name, continent or id"),
        _order: Optional[str] = Query("ASC", description="sort order ASC or DESC"),
        _start: int = Query(0, alias="_start"),
        _end: int = Query(len(COUNTRIES), alias="_end"),
    ) -> List[CountryAlpha2Model]:

    if _start and _end and (_start < 0 or _end < _start):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST,
                            detail="Invalid start or end index")

    alpha2s = [CountryAlpha2Model(id=country["iso2"], country_name=country["name"], continent=country["continent"]) for country in COUNTRIES]

    if _sort:
        if _sort == "id":
            alpha2s = sorted(alpha2s, key=lambda country: country.id, reverse=_order == "DESC")
        elif _sort == "country_name":
            alpha2s = sorted(alpha2s, key=lambda country: country.country_name, reverse=_order == "DESC")
        elif _sort == "continent":
            alpha2s = sorted(alpha2s, key=lambda country: country.continent, reverse=_order == "DESC")

    if _start:
        alpha2s = alpha2s[_start:]
    if _end:
        alpha2s = alpha2s[:_end]
    response.headers['X-Total-Count'] = str(len(COUNTRIES))
    return alpha2s


@router.get('/iso2/{alpha2:str}')
def get_country_by_iso2(alpha2: str) -> CountryAlpha2Model:
    for country in COUNTRIES:
        if country["iso2"] == alpha2:
            return CountryAlpha2Model(id=country["iso2"], country_name=country["name"], continent=country["continent"])

    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Country not found")
